// Generated by scripts/poc-codegen for AWS::S3::Bucket — DO NOT EDIT

// Source models: CFn registry schema + s3-2006-03-01.json

function toNum(v: unknown): number | undefined {
  if (v === undefined || v === null) return undefined;
  if (typeof v === 'number') return v;
  const n = Number(v);
  if (Number.isNaN(n)) throw new Error(`expected a number, got: ${JSON.stringify(v)}`);
  return n;
}
function toBool(v: unknown): boolean | undefined {
  if (v === undefined || v === null) return undefined;
  if (typeof v === 'boolean') return v;
  if (v === 'true' || v === 'True') return true;
  if (v === 'false' || v === 'False') return false;
  throw new Error(`expected a boolean, got: ${JSON.stringify(v)}`);
}
function toDateV(v: unknown): Date | undefined {
  if (v === undefined || v === null) return undefined;
  if (v instanceof Date) return v;
  const d = typeof v === 'string' || typeof v === 'number' ? new Date(v) : new Date(NaN);
  if (Number.isNaN(d.getTime())) throw new Error(`unparsable time value: ${JSON.stringify(v)}`);
  return d;
}
function toJsonString(v: unknown): string | undefined {
  if (v === undefined || v === null) return undefined;
  return typeof v === 'string' ? v : JSON.stringify(v);
}

// #top(CreateBucket) -> CreateBucketRequest
function map_0(input: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  // UNMATCHED: 'AbacStatus' (string) — no SDK member; verify: CFn-only field or silent drop
  // UNMATCHED: 'AccelerateConfiguration' (structure) — no SDK member; verify: CFn-only field or silent drop
  // UNMATCHED: 'AccessControl' (string) — no SDK member; verify: CFn-only field or silent drop
  // UNMATCHED: 'AnalyticsConfigurations' (list) — no SDK member; verify: CFn-only field or silent drop
  // UNMATCHED: 'BucketEncryption' (structure) — no SDK member; verify: CFn-only field or silent drop
  // COLLISION (NOT emitted): 'BucketName' -> 'BucketNamespace' — fuzzy-matched to "BucketNamespace" (overlap 0.67); collides with 'BucketNamespace' on SDK member 'BucketNamespace' — NOT emitted; needs an override-table decision
  // RENAME-CANDIDATE (NOT emitted; confirm via override table): 'BucketNamePrefix' -> 'Bucket' (fuzzy-matched to "Bucket" (overlap 0.38))
  {
    const v = input['BucketNamespace'];
    if (v !== undefined) out['BucketNamespace'] = v;
  }
  // UNMATCHED: 'CorsConfiguration' (structure) — no SDK member; verify: CFn-only field or silent drop
  // UNMATCHED: 'IntelligentTieringConfigurations' (list) — no SDK member; verify: CFn-only field or silent drop
  // UNMATCHED: 'InventoryConfigurations' (list) — no SDK member; verify: CFn-only field or silent drop
  // UNMATCHED: 'LifecycleConfiguration' (structure) — no SDK member; verify: CFn-only field or silent drop
  // UNMATCHED: 'LoggingConfiguration' (structure) — no SDK member; verify: CFn-only field or silent drop
  // UNMATCHED: 'MetadataConfiguration' (structure) — no SDK member; verify: CFn-only field or silent drop
  // UNMATCHED: 'MetadataTableConfiguration' (structure) — no SDK member; verify: CFn-only field or silent drop
  // UNMATCHED: 'MetricsConfigurations' (list) — no SDK member; verify: CFn-only field or silent drop
  // UNMATCHED: 'NotificationConfiguration' (structure) — no SDK member; verify: CFn-only field or silent drop
  // UNMATCHED: 'ObjectLockConfiguration' (structure) — no SDK member; verify: CFn-only field or silent drop
  // RENAME-CANDIDATE (NOT emitted; confirm via override table): 'ObjectLockEnabled' -> 'ObjectLockEnabledForBucket' (fuzzy-matched to "ObjectLockEnabledForBucket" (overlap 0.65))
  // UNMATCHED: 'OwnershipControls' (structure) — no SDK member; verify: CFn-only field or silent drop
  // UNMATCHED: 'PublicAccessBlockConfiguration' (structure) — no SDK member; verify: CFn-only field or silent drop
  // UNMATCHED: 'ReplicationConfiguration' (structure) — no SDK member; verify: CFn-only field or silent drop
  // UNMATCHED: 'Tags' (list) — no SDK member; verify: CFn-only field or silent drop
  // UNMATCHED: 'VersioningConfiguration' (structure) — no SDK member; verify: CFn-only field or silent drop
  // UNMATCHED: 'WebsiteConfiguration' (structure) — no SDK member; verify: CFn-only field or silent drop
  return out;
}

// #top(UpdateBucketMetadataJournalTableConfiguration) -> UpdateBucketMetadataJournalTableConfigurationRequest
function map_1(input: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  // UNMATCHED: 'AbacStatus' (string) — no SDK member; verify: CFn-only field or silent drop
  // UNMATCHED: 'AccelerateConfiguration' (structure) — no SDK member; verify: CFn-only field or silent drop
  // UNMATCHED: 'AccessControl' (string) — no SDK member; verify: CFn-only field or silent drop
  // UNMATCHED: 'AnalyticsConfigurations' (list) — no SDK member; verify: CFn-only field or silent drop
  // UNMATCHED: 'BucketEncryption' (structure) — no SDK member; verify: CFn-only field or silent drop
  // RENAME-CANDIDATE (NOT emitted; confirm via override table): 'BucketName' -> 'Bucket' (fuzzy-matched to "Bucket" (overlap 0.60))
  // COLLISION (NOT emitted): 'BucketNamePrefix' -> 'Bucket' — fuzzy-matched to "Bucket" (overlap 0.38); collides with 'BucketName' on SDK member 'Bucket' — NOT emitted; needs an override-table decision
  // COLLISION (NOT emitted): 'BucketNamespace' -> 'Bucket' — fuzzy-matched to "Bucket" (overlap 0.40); collides with 'BucketName' on SDK member 'Bucket' — NOT emitted; needs an override-table decision
  // UNMATCHED: 'CorsConfiguration' (structure) — no SDK member; verify: CFn-only field or silent drop
  // UNMATCHED: 'IntelligentTieringConfigurations' (list) — no SDK member; verify: CFn-only field or silent drop
  // UNMATCHED: 'InventoryConfigurations' (list) — no SDK member; verify: CFn-only field or silent drop
  // UNMATCHED: 'LifecycleConfiguration' (structure) — no SDK member; verify: CFn-only field or silent drop
  // UNMATCHED: 'LoggingConfiguration' (structure) — no SDK member; verify: CFn-only field or silent drop
  // UNMATCHED: 'MetadataConfiguration' (structure) — no SDK member; verify: CFn-only field or silent drop
  // UNMATCHED: 'MetadataTableConfiguration' (structure) — no SDK member; verify: CFn-only field or silent drop
  // UNMATCHED: 'MetricsConfigurations' (list) — no SDK member; verify: CFn-only field or silent drop
  // UNMATCHED: 'NotificationConfiguration' (structure) — no SDK member; verify: CFn-only field or silent drop
  // UNMATCHED: 'ObjectLockConfiguration' (structure) — no SDK member; verify: CFn-only field or silent drop
  // UNMATCHED: 'ObjectLockEnabled' (boolean) — no SDK member; verify: CFn-only field or silent drop
  // UNMATCHED: 'OwnershipControls' (structure) — no SDK member; verify: CFn-only field or silent drop
  // UNMATCHED: 'PublicAccessBlockConfiguration' (structure) — no SDK member; verify: CFn-only field or silent drop
  // UNMATCHED: 'ReplicationConfiguration' (structure) — no SDK member; verify: CFn-only field or silent drop
  // UNMATCHED: 'Tags' (list) — no SDK member; verify: CFn-only field or silent drop
  // UNMATCHED: 'VersioningConfiguration' (structure) — no SDK member; verify: CFn-only field or silent drop
  // UNMATCHED: 'WebsiteConfiguration' (structure) — no SDK member; verify: CFn-only field or silent drop
  // TODO(required): SDK member 'JournalTableConfiguration' has no CFn source — synthesize it
  return out;
}

// #top(DeleteBucket) -> DeleteBucketRequest
function map_2(input: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  // UNMATCHED: 'AbacStatus' (string) — no SDK member; verify: CFn-only field or silent drop
  // UNMATCHED: 'AccelerateConfiguration' (structure) — no SDK member; verify: CFn-only field or silent drop
  // UNMATCHED: 'AccessControl' (string) — no SDK member; verify: CFn-only field or silent drop
  // UNMATCHED: 'AnalyticsConfigurations' (list) — no SDK member; verify: CFn-only field or silent drop
  // UNMATCHED: 'BucketEncryption' (structure) — no SDK member; verify: CFn-only field or silent drop
  // RENAME-CANDIDATE (NOT emitted; confirm via override table): 'BucketName' -> 'Bucket' (fuzzy-matched to "Bucket" (overlap 0.60))
  // COLLISION (NOT emitted): 'BucketNamePrefix' -> 'Bucket' — fuzzy-matched to "Bucket" (overlap 0.38); collides with 'BucketName' on SDK member 'Bucket' — NOT emitted; needs an override-table decision
  // COLLISION (NOT emitted): 'BucketNamespace' -> 'Bucket' — fuzzy-matched to "Bucket" (overlap 0.40); collides with 'BucketName' on SDK member 'Bucket' — NOT emitted; needs an override-table decision
  // UNMATCHED: 'CorsConfiguration' (structure) — no SDK member; verify: CFn-only field or silent drop
  // UNMATCHED: 'IntelligentTieringConfigurations' (list) — no SDK member; verify: CFn-only field or silent drop
  // UNMATCHED: 'InventoryConfigurations' (list) — no SDK member; verify: CFn-only field or silent drop
  // UNMATCHED: 'LifecycleConfiguration' (structure) — no SDK member; verify: CFn-only field or silent drop
  // UNMATCHED: 'LoggingConfiguration' (structure) — no SDK member; verify: CFn-only field or silent drop
  // UNMATCHED: 'MetadataConfiguration' (structure) — no SDK member; verify: CFn-only field or silent drop
  // UNMATCHED: 'MetadataTableConfiguration' (structure) — no SDK member; verify: CFn-only field or silent drop
  // UNMATCHED: 'MetricsConfigurations' (list) — no SDK member; verify: CFn-only field or silent drop
  // UNMATCHED: 'NotificationConfiguration' (structure) — no SDK member; verify: CFn-only field or silent drop
  // UNMATCHED: 'ObjectLockConfiguration' (structure) — no SDK member; verify: CFn-only field or silent drop
  // UNMATCHED: 'ObjectLockEnabled' (boolean) — no SDK member; verify: CFn-only field or silent drop
  // UNMATCHED: 'OwnershipControls' (structure) — no SDK member; verify: CFn-only field or silent drop
  // UNMATCHED: 'PublicAccessBlockConfiguration' (structure) — no SDK member; verify: CFn-only field or silent drop
  // UNMATCHED: 'ReplicationConfiguration' (structure) — no SDK member; verify: CFn-only field or silent drop
  // UNMATCHED: 'Tags' (list) — no SDK member; verify: CFn-only field or silent drop
  // UNMATCHED: 'VersioningConfiguration' (structure) — no SDK member; verify: CFn-only field or silent drop
  // UNMATCHED: 'WebsiteConfiguration' (structure) — no SDK member; verify: CFn-only field or silent drop
  return out;
}

/** CreateBucket (handlers) — input shape CreateBucketRequest */
export function buildCreateInput(properties: Record<string, unknown>): Record<string, unknown> {
  return map_0(properties);
}

/** UpdateBucketMetadataJournalTableConfiguration (handlers) — input shape UpdateBucketMetadataJournalTableConfigurationRequest */
export function buildUpdateInput(properties: Record<string, unknown>): Record<string, unknown> {
  return map_1(properties);
}

/** DeleteBucket (handlers) — input shape DeleteBucketRequest */
export function buildDeleteInput(properties: Record<string, unknown>): Record<string, unknown> {
  return map_2(properties);
}

