// Generated by scripts/poc-codegen for AWS::CloudWatch::AnomalyDetector — DO NOT EDIT

// Source models: CFn registry schema + cloudwatch-2010-08-01.json

function toNum(v: unknown): number | undefined {
  if (v === undefined || v === null) return undefined;
  if (typeof v === 'number') return v;
  const n = Number(v);
  if (Number.isNaN(n)) throw new Error(`expected a number, got: ${JSON.stringify(v)}`);
  return n;
}
function toBool(v: unknown): boolean | undefined {
  if (v === undefined || v === null) return undefined;
  if (typeof v === 'boolean') return v;
  if (v === 'true') return true;
  if (v === 'false') return false;
  throw new Error(`expected a boolean, got: ${JSON.stringify(v)}`);
}
function toDateV(v: unknown): Date | undefined {
  if (v === undefined || v === null) return undefined;
  if (v instanceof Date) return v;
  const d = typeof v === 'string' || typeof v === 'number' ? new Date(v) : new Date(NaN);
  if (Number.isNaN(d.getTime())) throw new Error(`unparsable time value: ${JSON.stringify(v)}`);
  return d;
}
function toJsonString(v: unknown): string | undefined {
  if (v === undefined || v === null) return undefined;
  return typeof v === 'string' ? v : JSON.stringify(v);
}

// Range -> Range
function map_6(input: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  {
    const v = input['EndTime'];
    if (v !== undefined) out['EndTime'] = toDateV(v);
  }
  {
    const v = input['StartTime'];
    if (v !== undefined) out['StartTime'] = toDateV(v);
  }
  return out;
}

// Configuration -> AnomalyDetectorConfiguration
function map_1(input: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  {
    const v = input['ExcludedTimeRanges'];
    if (v !== undefined) out['ExcludedTimeRanges'] = (v as unknown[]).map((e) => map_6(e as Record<string, unknown>));
  }
  // case-divergence: 'MetricTimeZone' -> 'MetricTimezone'
  {
    const v = input['MetricTimeZone'];
    if (v !== undefined) out['MetricTimezone'] = v;
  }
  return out;
}

// Dimension -> Dimension
function map_2(input: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  {
    const v = input['Name'];
    if (v !== undefined) out['Name'] = v;
  }
  {
    const v = input['Value'];
    if (v !== undefined) out['Value'] = v;
  }
  return out;
}

// MetricCharacteristics -> MetricCharacteristics
function map_3(input: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  {
    const v = input['PeriodicSpikes'];
    if (v !== undefined) out['PeriodicSpikes'] = v;
  }
  return out;
}

// Metric -> Metric
function map_9(input: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  {
    const v = input['Dimensions'];
    if (v !== undefined) out['Dimensions'] = (v as unknown[]).map((e) => map_2(e as Record<string, unknown>));
  }
  {
    const v = input['MetricName'];
    if (v !== undefined) out['MetricName'] = v;
  }
  {
    const v = input['Namespace'];
    if (v !== undefined) out['Namespace'] = v;
  }
  return out;
}

// MetricStat -> MetricStat
function map_8(input: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  {
    const v = input['Metric'];
    if (v !== undefined) out['Metric'] = map_9(v as Record<string, unknown>);
  }
  {
    const v = input['Period'];
    if (v !== undefined) out['Period'] = v;
  }
  {
    const v = input['Stat'];
    if (v !== undefined) out['Stat'] = v;
  }
  {
    const v = input['Unit'];
    if (v !== undefined) out['Unit'] = v;
  }
  return out;
}

// MetricDataQuery -> MetricDataQuery
function map_7(input: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  {
    const v = input['AccountId'];
    if (v !== undefined) out['AccountId'] = v;
  }
  {
    const v = input['Expression'];
    if (v !== undefined) out['Expression'] = v;
  }
  {
    const v = input['Id'];
    if (v !== undefined) out['Id'] = v;
  }
  {
    const v = input['Label'];
    if (v !== undefined) out['Label'] = v;
  }
  {
    const v = input['MetricStat'];
    if (v !== undefined) out['MetricStat'] = map_8(v as Record<string, unknown>);
  }
  {
    const v = input['Period'];
    if (v !== undefined) out['Period'] = v;
  }
  {
    const v = input['ReturnData'];
    if (v !== undefined) out['ReturnData'] = v;
  }
  return out;
}

// MetricMathAnomalyDetector -> MetricMathAnomalyDetector
function map_4(input: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  {
    const v = input['MetricDataQueries'];
    if (v !== undefined) out['MetricDataQueries'] = (v as unknown[]).map((e) => map_7(e as Record<string, unknown>));
  }
  return out;
}

// SingleMetricAnomalyDetector -> SingleMetricAnomalyDetector
function map_5(input: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  {
    const v = input['AccountId'];
    if (v !== undefined) out['AccountId'] = v;
  }
  {
    const v = input['Dimensions'];
    if (v !== undefined) out['Dimensions'] = (v as unknown[]).map((e) => map_2(e as Record<string, unknown>));
  }
  {
    const v = input['MetricName'];
    if (v !== undefined) out['MetricName'] = v;
  }
  {
    const v = input['Namespace'];
    if (v !== undefined) out['Namespace'] = v;
  }
  {
    const v = input['Stat'];
    if (v !== undefined) out['Stat'] = v;
  }
  return out;
}

// #top(PutAnomalyDetector) -> PutAnomalyDetectorInput
function map_0(input: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  {
    const v = input['Configuration'];
    if (v !== undefined) out['Configuration'] = map_1(v as Record<string, unknown>);
  }
  {
    const v = input['Dimensions'];
    if (v !== undefined) out['Dimensions'] = (v as unknown[]).map((e) => map_2(e as Record<string, unknown>));
  }
  {
    const v = input['MetricCharacteristics'];
    if (v !== undefined) out['MetricCharacteristics'] = map_3(v as Record<string, unknown>);
  }
  {
    const v = input['MetricMathAnomalyDetector'];
    if (v !== undefined) out['MetricMathAnomalyDetector'] = map_4(v as Record<string, unknown>);
  }
  {
    const v = input['MetricName'];
    if (v !== undefined) out['MetricName'] = v;
  }
  {
    const v = input['Namespace'];
    if (v !== undefined) out['Namespace'] = v;
  }
  {
    const v = input['SingleMetricAnomalyDetector'];
    if (v !== undefined) out['SingleMetricAnomalyDetector'] = map_5(v as Record<string, unknown>);
  }
  {
    const v = input['Stat'];
    if (v !== undefined) out['Stat'] = v;
  }
  return out;
}

// #top(DeleteAnomalyDetector) -> DeleteAnomalyDetectorInput
function map_10(input: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  // UNMATCHED: 'Configuration' (structure) — no SDK member; verify: CFn-only field or silent drop
  {
    const v = input['Dimensions'];
    if (v !== undefined) out['Dimensions'] = (v as unknown[]).map((e) => map_2(e as Record<string, unknown>));
  }
  // UNMATCHED: 'MetricCharacteristics' (structure) — no SDK member; verify: CFn-only field or silent drop
  {
    const v = input['MetricMathAnomalyDetector'];
    if (v !== undefined) out['MetricMathAnomalyDetector'] = map_4(v as Record<string, unknown>);
  }
  {
    const v = input['MetricName'];
    if (v !== undefined) out['MetricName'] = v;
  }
  {
    const v = input['Namespace'];
    if (v !== undefined) out['Namespace'] = v;
  }
  {
    const v = input['SingleMetricAnomalyDetector'];
    if (v !== undefined) out['SingleMetricAnomalyDetector'] = map_5(v as Record<string, unknown>);
  }
  {
    const v = input['Stat'];
    if (v !== undefined) out['Stat'] = v;
  }
  return out;
}

/** PutAnomalyDetector (verb-heuristic) — input shape PutAnomalyDetectorInput */
export function buildCreateInput(properties: Record<string, unknown>): Record<string, unknown> {
  return map_0(properties);
}

/** PutAnomalyDetector (verb-heuristic) — input shape PutAnomalyDetectorInput */
export function buildUpdateInput(properties: Record<string, unknown>): Record<string, unknown> {
  return map_0(properties);
}

/** DeleteAnomalyDetector (verb-heuristic) — input shape DeleteAnomalyDetectorInput */
export function buildDeleteInput(properties: Record<string, unknown>): Record<string, unknown> {
  return map_10(properties);
}

