// Generated by scripts/poc-codegen for AWS::ECS::Service — DO NOT EDIT

// Source models: CFn registry schema + ecs-2014-11-13.json

function toNum(v: unknown): number | undefined {
  if (v === undefined || v === null) return undefined;
  if (typeof v === 'number') return v;
  const n = Number(v);
  if (Number.isNaN(n)) throw new Error(`expected a number, got: ${JSON.stringify(v)}`);
  return n;
}
function toBool(v: unknown): boolean | undefined {
  if (v === undefined || v === null) return undefined;
  if (typeof v === 'boolean') return v;
  if (v === 'true' || v === 'True') return true;
  if (v === 'false' || v === 'False') return false;
  throw new Error(`expected a boolean, got: ${JSON.stringify(v)}`);
}
function toDateV(v: unknown): Date | undefined {
  if (v === undefined || v === null) return undefined;
  if (v instanceof Date) return v;
  const d = typeof v === 'string' || typeof v === 'number' ? new Date(v) : new Date(NaN);
  if (Number.isNaN(d.getTime())) throw new Error(`unparsable time value: ${JSON.stringify(v)}`);
  return d;
}
function toJsonString(v: unknown): string | undefined {
  if (v === undefined || v === null) return undefined;
  return typeof v === 'string' ? v : JSON.stringify(v);
}

// CapacityProviderStrategyItem -> CapacityProviderStrategyItem
function map_1(input: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  {
    const v = input['Base'];
    if (v !== undefined) out['base'] = v;
  }
  {
    const v = input['CapacityProvider'];
    if (v !== undefined) out['capacityProvider'] = v;
  }
  {
    const v = input['Weight'];
    if (v !== undefined) out['weight'] = v;
  }
  return out;
}

// DeploymentAlarms -> DeploymentAlarms
function map_13(input: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  {
    const v = input['AlarmNames'];
    if (v !== undefined) out['alarmNames'] = v;
  }
  {
    const v = input['Enable'];
    if (v !== undefined) out['enable'] = v;
  }
  {
    const v = input['Rollback'];
    if (v !== undefined) out['rollback'] = v;
  }
  return out;
}

// CanaryConfiguration -> CanaryConfiguration
function map_14(input: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  {
    const v = input['CanaryBakeTimeInMinutes'];
    if (v !== undefined) out['canaryBakeTimeInMinutes'] = v;
  }
  {
    const v = input['CanaryPercent'];
    if (v !== undefined) out['canaryPercent'] = v;
  }
  return out;
}

// ThresholdConfiguration -> ThresholdConfiguration
function map_18(input: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  {
    const v = input['Type'];
    if (v !== undefined) out['type'] = v;
  }
  {
    const v = input['Value'];
    if (v !== undefined) out['value'] = v;
  }
  return out;
}

// DeploymentCircuitBreaker -> DeploymentCircuitBreaker
function map_15(input: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  {
    const v = input['Enable'];
    if (v !== undefined) out['enable'] = v;
  }
  {
    const v = input['ResetOnHealthyTask'];
    if (v !== undefined) out['resetOnHealthyTask'] = v;
  }
  {
    const v = input['Rollback'];
    if (v !== undefined) out['rollback'] = v;
  }
  {
    const v = input['ThresholdConfiguration'];
    if (v !== undefined) out['thresholdConfiguration'] = map_18(v as Record<string, unknown>);
  }
  return out;
}

// HookTimeoutConfig -> DeploymentLifecycleHookTimeoutConfiguration
function map_19(input: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  {
    const v = input['Action'];
    if (v !== undefined) out['action'] = v;
  }
  {
    const v = input['TimeoutInMinutes'];
    if (v !== undefined) out['timeoutInMinutes'] = v;
  }
  return out;
}

// DeploymentLifecycleHook -> DeploymentLifecycleHook
function map_16(input: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  {
    const v = input['HookDetails'];
    if (v !== undefined) out['hookDetails'] = v;
  }
  {
    const v = input['HookTargetArn'];
    if (v !== undefined) out['hookTargetArn'] = v;
  }
  {
    const v = input['LifecycleStages'];
    if (v !== undefined) out['lifecycleStages'] = v;
  }
  {
    const v = input['RoleArn'];
    if (v !== undefined) out['roleArn'] = v;
  }
  {
    const v = input['TargetType'];
    if (v !== undefined) out['targetType'] = v;
  }
  {
    const v = input['TimeoutConfiguration'];
    if (v !== undefined) out['timeoutConfiguration'] = map_19(v as Record<string, unknown>);
  }
  return out;
}

// LinearConfiguration -> LinearConfiguration
function map_17(input: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  {
    const v = input['StepBakeTimeInMinutes'];
    if (v !== undefined) out['stepBakeTimeInMinutes'] = v;
  }
  {
    const v = input['StepPercent'];
    if (v !== undefined) out['stepPercent'] = v;
  }
  return out;
}

// DeploymentConfiguration -> DeploymentConfiguration
function map_2(input: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  {
    const v = input['Alarms'];
    if (v !== undefined) out['alarms'] = map_13(v as Record<string, unknown>);
  }
  {
    const v = input['BakeTimeInMinutes'];
    if (v !== undefined) out['bakeTimeInMinutes'] = v;
  }
  {
    const v = input['CanaryConfiguration'];
    if (v !== undefined) out['canaryConfiguration'] = map_14(v as Record<string, unknown>);
  }
  {
    const v = input['DeploymentCircuitBreaker'];
    if (v !== undefined) out['deploymentCircuitBreaker'] = map_15(v as Record<string, unknown>);
  }
  {
    const v = input['LifecycleHooks'];
    if (v !== undefined) out['lifecycleHooks'] = (v as unknown[]).map((e) => map_16(e as Record<string, unknown>));
  }
  {
    const v = input['LinearConfiguration'];
    if (v !== undefined) out['linearConfiguration'] = map_17(v as Record<string, unknown>);
  }
  {
    const v = input['MaximumPercent'];
    if (v !== undefined) out['maximumPercent'] = v;
  }
  {
    const v = input['MinimumHealthyPercent'];
    if (v !== undefined) out['minimumHealthyPercent'] = v;
  }
  {
    const v = input['Strategy'];
    if (v !== undefined) out['strategy'] = v;
  }
  return out;
}

// DeploymentController -> DeploymentController
function map_3(input: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  {
    const v = input['Type'];
    if (v !== undefined) out['type'] = v;
  }
  return out;
}

// AdvancedConfiguration -> AdvancedConfiguration
function map_20(input: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  {
    const v = input['AlternateTargetGroupArn'];
    if (v !== undefined) out['alternateTargetGroupArn'] = v;
  }
  {
    const v = input['ProductionListenerRule'];
    if (v !== undefined) out['productionListenerRule'] = v;
  }
  {
    const v = input['RoleArn'];
    if (v !== undefined) out['roleArn'] = v;
  }
  {
    const v = input['TestListenerRule'];
    if (v !== undefined) out['testListenerRule'] = v;
  }
  return out;
}

// LoadBalancer -> LoadBalancer
function map_4(input: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  {
    const v = input['AdvancedConfiguration'];
    if (v !== undefined) out['advancedConfiguration'] = map_20(v as Record<string, unknown>);
  }
  {
    const v = input['ContainerName'];
    if (v !== undefined) out['containerName'] = v;
  }
  {
    const v = input['ContainerPort'];
    if (v !== undefined) out['containerPort'] = v;
  }
  {
    const v = input['LoadBalancerName'];
    if (v !== undefined) out['loadBalancerName'] = v;
  }
  {
    const v = input['TargetGroupArn'];
    if (v !== undefined) out['targetGroupArn'] = v;
  }
  return out;
}

// MetricConfiguration -> MetricConfiguration
function map_21(input: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  {
    const v = input['MetricNames'];
    if (v !== undefined) out['metricNames'] = v;
  }
  {
    const v = input['ResolutionSeconds'];
    if (v !== undefined) out['resolutionSeconds'] = v;
  }
  return out;
}

// MonitoringConfiguration -> MonitoringConfiguration
function map_5(input: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  {
    const v = input['MetricConfigurations'];
    if (v !== undefined) out['metricConfigurations'] = (v as unknown[]).map((e) => map_21(e as Record<string, unknown>));
  }
  return out;
}

// AwsVpcConfiguration -> AwsVpcConfiguration
function map_22(input: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  {
    const v = input['AssignPublicIp'];
    if (v !== undefined) out['assignPublicIp'] = v;
  }
  {
    const v = input['SecurityGroups'];
    if (v !== undefined) out['securityGroups'] = v;
  }
  {
    const v = input['Subnets'];
    if (v !== undefined) out['subnets'] = v;
  }
  return out;
}

// NetworkConfiguration -> NetworkConfiguration
function map_6(input: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  {
    const v = input['AwsvpcConfiguration'];
    if (v !== undefined) out['awsvpcConfiguration'] = map_22(v as Record<string, unknown>);
  }
  return out;
}

// PlacementConstraint -> PlacementConstraint
function map_7(input: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  {
    const v = input['Expression'];
    if (v !== undefined) out['expression'] = v;
  }
  {
    const v = input['Type'];
    if (v !== undefined) out['type'] = v;
  }
  return out;
}

// ServiceConnectAccessLogConfiguration -> ServiceConnectAccessLogConfiguration
function map_23(input: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  {
    const v = input['Format'];
    if (v !== undefined) out['format'] = v;
  }
  {
    const v = input['IncludeQueryParameters'];
    if (v !== undefined) out['includeQueryParameters'] = v;
  }
  return out;
}

// Secret -> Secret
function map_26(input: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  {
    const v = input['Name'];
    if (v !== undefined) out['name'] = v;
  }
  {
    const v = input['ValueFrom'];
    if (v !== undefined) out['valueFrom'] = v;
  }
  return out;
}

// LogConfiguration -> LogConfiguration
function map_24(input: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  {
    const v = input['LogDriver'];
    if (v !== undefined) out['logDriver'] = v;
  }
  {
    const v = input['Options'];
    if (v !== undefined) out['options'] = v;
  }
  {
    const v = input['SecretOptions'];
    if (v !== undefined) out['secretOptions'] = (v as unknown[]).map((e) => map_26(e as Record<string, unknown>));
  }
  return out;
}

// ServiceConnectTestTrafficRulesHeaderValue -> ServiceConnectTestTrafficHeaderMatchRules
function map_32(input: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  {
    const v = input['Exact'];
    if (v !== undefined) out['exact'] = v;
  }
  return out;
}

// ServiceConnectTestTrafficRulesHeader -> ServiceConnectTestTrafficHeaderRules
function map_31(input: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  {
    const v = input['Name'];
    if (v !== undefined) out['name'] = v;
  }
  {
    const v = input['Value'];
    if (v !== undefined) out['value'] = map_32(v as Record<string, unknown>);
  }
  return out;
}

// ServiceConnectTestTrafficRules -> ServiceConnectTestTrafficRules
function map_30(input: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  {
    const v = input['Header'];
    if (v !== undefined) out['header'] = map_31(v as Record<string, unknown>);
  }
  return out;
}

// ServiceConnectClientAlias -> ServiceConnectClientAlias
function map_27(input: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  {
    const v = input['DnsName'];
    if (v !== undefined) out['dnsName'] = v;
  }
  {
    const v = input['Port'];
    if (v !== undefined) out['port'] = v;
  }
  {
    const v = input['TestTrafficRules'];
    if (v !== undefined) out['testTrafficRules'] = map_30(v as Record<string, unknown>);
  }
  return out;
}

// TimeoutConfiguration -> TimeoutConfiguration
function map_28(input: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  {
    const v = input['IdleTimeoutSeconds'];
    if (v !== undefined) out['idleTimeoutSeconds'] = v;
  }
  {
    const v = input['PerRequestTimeoutSeconds'];
    if (v !== undefined) out['perRequestTimeoutSeconds'] = v;
  }
  return out;
}

// ServiceConnectTlsCertificateAuthority -> ServiceConnectTlsCertificateAuthority
function map_33(input: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  {
    const v = input['AwsPcaAuthorityArn'];
    if (v !== undefined) out['awsPcaAuthorityArn'] = v;
  }
  return out;
}

// ServiceConnectTlsConfiguration -> ServiceConnectTlsConfiguration
function map_29(input: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  {
    const v = input['IssuerCertificateAuthority'];
    if (v !== undefined) out['issuerCertificateAuthority'] = map_33(v as Record<string, unknown>);
  }
  {
    const v = input['KmsKey'];
    if (v !== undefined) out['kmsKey'] = v;
  }
  {
    const v = input['RoleArn'];
    if (v !== undefined) out['roleArn'] = v;
  }
  return out;
}

// ServiceConnectService -> ServiceConnectService
function map_25(input: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  {
    const v = input['ClientAliases'];
    if (v !== undefined) out['clientAliases'] = (v as unknown[]).map((e) => map_27(e as Record<string, unknown>));
  }
  {
    const v = input['DiscoveryName'];
    if (v !== undefined) out['discoveryName'] = v;
  }
  {
    const v = input['IngressPortOverride'];
    if (v !== undefined) out['ingressPortOverride'] = v;
  }
  {
    const v = input['PortName'];
    if (v !== undefined) out['portName'] = v;
  }
  {
    const v = input['Timeout'];
    if (v !== undefined) out['timeout'] = map_28(v as Record<string, unknown>);
  }
  {
    const v = input['Tls'];
    if (v !== undefined) out['tls'] = map_29(v as Record<string, unknown>);
  }
  return out;
}

// ServiceConnectConfiguration -> ServiceConnectConfiguration
function map_8(input: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  {
    const v = input['AccessLogConfiguration'];
    if (v !== undefined) out['accessLogConfiguration'] = map_23(v as Record<string, unknown>);
  }
  {
    const v = input['Enabled'];
    if (v !== undefined) out['enabled'] = v;
  }
  {
    const v = input['LogConfiguration'];
    if (v !== undefined) out['logConfiguration'] = map_24(v as Record<string, unknown>);
  }
  {
    const v = input['Namespace'];
    if (v !== undefined) out['namespace'] = v;
  }
  {
    const v = input['Services'];
    if (v !== undefined) out['services'] = (v as unknown[]).map((e) => map_25(e as Record<string, unknown>));
  }
  return out;
}

// ServiceRegistry -> ServiceRegistry
function map_9(input: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  {
    const v = input['ContainerName'];
    if (v !== undefined) out['containerName'] = v;
  }
  {
    const v = input['ContainerPort'];
    if (v !== undefined) out['containerPort'] = v;
  }
  {
    const v = input['Port'];
    if (v !== undefined) out['port'] = v;
  }
  {
    const v = input['RegistryArn'];
    if (v !== undefined) out['registryArn'] = v;
  }
  return out;
}

// Tag -> Tag
function map_10(input: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  {
    const v = input['Key'];
    if (v !== undefined) out['key'] = v;
  }
  {
    const v = input['Value'];
    if (v !== undefined) out['value'] = v;
  }
  return out;
}

// EBSTagSpecification -> EBSTagSpecification
function map_35(input: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  {
    const v = input['PropagateTags'];
    if (v !== undefined) out['propagateTags'] = v;
  }
  {
    const v = input['ResourceType'];
    if (v !== undefined) out['resourceType'] = v;
  }
  {
    const v = input['Tags'];
    if (v !== undefined) out['tags'] = (v as unknown[]).map((e) => map_10(e as Record<string, unknown>));
  }
  return out;
}

// ServiceManagedEBSVolumeConfiguration -> ServiceManagedEBSVolumeConfiguration
function map_34(input: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  {
    const v = input['Encrypted'];
    if (v !== undefined) out['encrypted'] = v;
  }
  {
    const v = input['FilesystemType'];
    if (v !== undefined) out['filesystemType'] = v;
  }
  {
    const v = input['Iops'];
    if (v !== undefined) out['iops'] = v;
  }
  {
    const v = input['KmsKeyId'];
    if (v !== undefined) out['kmsKeyId'] = v;
  }
  {
    const v = input['RoleArn'];
    if (v !== undefined) out['roleArn'] = v;
  }
  {
    const v = input['SizeInGiB'];
    if (v !== undefined) out['sizeInGiB'] = v;
  }
  {
    const v = input['SnapshotId'];
    if (v !== undefined) out['snapshotId'] = v;
  }
  {
    const v = input['TagSpecifications'];
    if (v !== undefined) out['tagSpecifications'] = (v as unknown[]).map((e) => map_35(e as Record<string, unknown>));
  }
  {
    const v = input['Throughput'];
    if (v !== undefined) out['throughput'] = v;
  }
  {
    const v = input['VolumeInitializationRate'];
    if (v !== undefined) out['volumeInitializationRate'] = v;
  }
  {
    const v = input['VolumeType'];
    if (v !== undefined) out['volumeType'] = v;
  }
  return out;
}

// ServiceVolumeConfiguration -> ServiceVolumeConfiguration
function map_11(input: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  {
    const v = input['ManagedEBSVolume'];
    if (v !== undefined) out['managedEBSVolume'] = map_34(v as Record<string, unknown>);
  }
  {
    const v = input['Name'];
    if (v !== undefined) out['name'] = v;
  }
  return out;
}

// VpcLatticeConfiguration -> VpcLatticeConfiguration
function map_12(input: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  {
    const v = input['PortName'];
    if (v !== undefined) out['portName'] = v;
  }
  {
    const v = input['RoleArn'];
    if (v !== undefined) out['roleArn'] = v;
  }
  {
    const v = input['TargetGroupArn'];
    if (v !== undefined) out['targetGroupArn'] = v;
  }
  return out;
}

// #top(CreateService) -> CreateServiceRequest
function map_0(input: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  {
    const v = input['AvailabilityZoneRebalancing'];
    if (v !== undefined) out['availabilityZoneRebalancing'] = v;
  }
  {
    const v = input['CapacityProviderStrategy'];
    if (v !== undefined) out['capacityProviderStrategy'] = (v as unknown[]).map((e) => map_1(e as Record<string, unknown>));
  }
  {
    const v = input['Cluster'];
    if (v !== undefined) out['cluster'] = v;
  }
  {
    const v = input['DeploymentConfiguration'];
    if (v !== undefined) out['deploymentConfiguration'] = map_2(v as Record<string, unknown>);
  }
  {
    const v = input['DeploymentController'];
    if (v !== undefined) out['deploymentController'] = map_3(v as Record<string, unknown>);
  }
  {
    const v = input['DesiredCount'];
    if (v !== undefined) out['desiredCount'] = v;
  }
  {
    const v = input['EnableECSManagedTags'];
    if (v !== undefined) out['enableECSManagedTags'] = v;
  }
  {
    const v = input['EnableExecuteCommand'];
    if (v !== undefined) out['enableExecuteCommand'] = v;
  }
  // UNMATCHED: 'ForceNewDeployment' (structure) — no SDK member; verify: CFn-only field or silent drop
  {
    const v = input['HealthCheckGracePeriodSeconds'];
    if (v !== undefined) out['healthCheckGracePeriodSeconds'] = v;
  }
  {
    const v = input['LaunchType'];
    if (v !== undefined) out['launchType'] = v;
  }
  {
    const v = input['LoadBalancers'];
    if (v !== undefined) out['loadBalancers'] = (v as unknown[]).map((e) => map_4(e as Record<string, unknown>));
  }
  {
    const v = input['Monitoring'];
    if (v !== undefined) out['monitoring'] = map_5(v as Record<string, unknown>);
  }
  {
    const v = input['NetworkConfiguration'];
    if (v !== undefined) out['networkConfiguration'] = map_6(v as Record<string, unknown>);
  }
  {
    const v = input['PlacementConstraints'];
    if (v !== undefined) out['placementConstraints'] = (v as unknown[]).map((e) => map_7(e as Record<string, unknown>));
  }
  // RENAME-CANDIDATE (NOT emitted; confirm via override table): 'PlacementStrategies' -> 'placementStrategy' (fuzzy-matched to "placementStrategy" (overlap 0.84))
  {
    const v = input['PlatformVersion'];
    if (v !== undefined) out['platformVersion'] = v;
  }
  {
    const v = input['PropagateTags'];
    if (v !== undefined) out['propagateTags'] = v;
  }
  {
    const v = input['Role'];
    if (v !== undefined) out['role'] = v;
  }
  {
    const v = input['SchedulingStrategy'];
    if (v !== undefined) out['schedulingStrategy'] = v;
  }
  {
    const v = input['ServiceConnectConfiguration'];
    if (v !== undefined) out['serviceConnectConfiguration'] = map_8(v as Record<string, unknown>);
  }
  {
    const v = input['ServiceName'];
    if (v !== undefined) out['serviceName'] = v;
  }
  {
    const v = input['ServiceRegistries'];
    if (v !== undefined) out['serviceRegistries'] = (v as unknown[]).map((e) => map_9(e as Record<string, unknown>));
  }
  {
    const v = input['Tags'];
    if (v !== undefined) out['tags'] = (v as unknown[]).map((e) => map_10(e as Record<string, unknown>));
  }
  {
    const v = input['TaskDefinition'];
    if (v !== undefined) out['taskDefinition'] = v;
  }
  {
    const v = input['VolumeConfigurations'];
    if (v !== undefined) out['volumeConfigurations'] = (v as unknown[]).map((e) => map_11(e as Record<string, unknown>));
  }
  {
    const v = input['VpcLatticeConfigurations'];
    if (v !== undefined) out['vpcLatticeConfigurations'] = (v as unknown[]).map((e) => map_12(e as Record<string, unknown>));
  }
  return out;
}

// #top(UpdateService) -> UpdateServiceRequest
function map_36(input: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  {
    const v = input['AvailabilityZoneRebalancing'];
    if (v !== undefined) out['availabilityZoneRebalancing'] = v;
  }
  {
    const v = input['CapacityProviderStrategy'];
    if (v !== undefined) out['capacityProviderStrategy'] = (v as unknown[]).map((e) => map_1(e as Record<string, unknown>));
  }
  {
    const v = input['Cluster'];
    if (v !== undefined) out['cluster'] = v;
  }
  {
    const v = input['DeploymentConfiguration'];
    if (v !== undefined) out['deploymentConfiguration'] = map_2(v as Record<string, unknown>);
  }
  {
    const v = input['DeploymentController'];
    if (v !== undefined) out['deploymentController'] = map_3(v as Record<string, unknown>);
  }
  {
    const v = input['DesiredCount'];
    if (v !== undefined) out['desiredCount'] = v;
  }
  {
    const v = input['EnableECSManagedTags'];
    if (v !== undefined) out['enableECSManagedTags'] = v;
  }
  {
    const v = input['EnableExecuteCommand'];
    if (v !== undefined) out['enableExecuteCommand'] = v;
  }
  // UNSUPPORTED: 'ForceNewDeployment' -> 'forceNewDeployment' (type-incompatible: CFn structure vs SDK boolean)
  {
    const v = input['HealthCheckGracePeriodSeconds'];
    if (v !== undefined) out['healthCheckGracePeriodSeconds'] = v;
  }
  // UNMATCHED: 'LaunchType' (string) — no SDK member; verify: CFn-only field or silent drop
  {
    const v = input['LoadBalancers'];
    if (v !== undefined) out['loadBalancers'] = (v as unknown[]).map((e) => map_4(e as Record<string, unknown>));
  }
  {
    const v = input['Monitoring'];
    if (v !== undefined) out['monitoring'] = map_5(v as Record<string, unknown>);
  }
  {
    const v = input['NetworkConfiguration'];
    if (v !== undefined) out['networkConfiguration'] = map_6(v as Record<string, unknown>);
  }
  {
    const v = input['PlacementConstraints'];
    if (v !== undefined) out['placementConstraints'] = (v as unknown[]).map((e) => map_7(e as Record<string, unknown>));
  }
  // RENAME-CANDIDATE (NOT emitted; confirm via override table): 'PlacementStrategies' -> 'placementStrategy' (fuzzy-matched to "placementStrategy" (overlap 0.84))
  {
    const v = input['PlatformVersion'];
    if (v !== undefined) out['platformVersion'] = v;
  }
  {
    const v = input['PropagateTags'];
    if (v !== undefined) out['propagateTags'] = v;
  }
  // UNMATCHED: 'Role' (string) — no SDK member; verify: CFn-only field or silent drop
  // UNMATCHED: 'SchedulingStrategy' (string) — no SDK member; verify: CFn-only field or silent drop
  {
    const v = input['ServiceConnectConfiguration'];
    if (v !== undefined) out['serviceConnectConfiguration'] = map_8(v as Record<string, unknown>);
  }
  // RENAME-CANDIDATE (NOT emitted; confirm via override table): 'ServiceName' -> 'service' (fuzzy-matched to "service" (overlap 0.64))
  {
    const v = input['ServiceRegistries'];
    if (v !== undefined) out['serviceRegistries'] = (v as unknown[]).map((e) => map_9(e as Record<string, unknown>));
  }
  // UNMATCHED: 'Tags' (list) — no SDK member; verify: CFn-only field or silent drop
  {
    const v = input['TaskDefinition'];
    if (v !== undefined) out['taskDefinition'] = v;
  }
  {
    const v = input['VolumeConfigurations'];
    if (v !== undefined) out['volumeConfigurations'] = (v as unknown[]).map((e) => map_11(e as Record<string, unknown>));
  }
  {
    const v = input['VpcLatticeConfigurations'];
    if (v !== undefined) out['vpcLatticeConfigurations'] = (v as unknown[]).map((e) => map_12(e as Record<string, unknown>));
  }
  return out;
}

// #top(DeleteService) -> DeleteServiceRequest
function map_37(input: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  // UNMATCHED: 'AvailabilityZoneRebalancing' (string) — no SDK member; verify: CFn-only field or silent drop
  // UNMATCHED: 'CapacityProviderStrategy' (list) — no SDK member; verify: CFn-only field or silent drop
  {
    const v = input['Cluster'];
    if (v !== undefined) out['cluster'] = v;
  }
  // UNMATCHED: 'DeploymentConfiguration' (structure) — no SDK member; verify: CFn-only field or silent drop
  // UNMATCHED: 'DeploymentController' (structure) — no SDK member; verify: CFn-only field or silent drop
  // UNMATCHED: 'DesiredCount' (number) — no SDK member; verify: CFn-only field or silent drop
  // UNMATCHED: 'EnableECSManagedTags' (boolean) — no SDK member; verify: CFn-only field or silent drop
  // UNMATCHED: 'EnableExecuteCommand' (boolean) — no SDK member; verify: CFn-only field or silent drop
  // UNMATCHED: 'ForceNewDeployment' (structure) — no SDK member; verify: CFn-only field or silent drop
  // UNMATCHED: 'HealthCheckGracePeriodSeconds' (number) — no SDK member; verify: CFn-only field or silent drop
  // UNMATCHED: 'LaunchType' (string) — no SDK member; verify: CFn-only field or silent drop
  // UNMATCHED: 'LoadBalancers' (list) — no SDK member; verify: CFn-only field or silent drop
  // UNMATCHED: 'Monitoring' (structure) — no SDK member; verify: CFn-only field or silent drop
  // UNMATCHED: 'NetworkConfiguration' (structure) — no SDK member; verify: CFn-only field or silent drop
  // UNMATCHED: 'PlacementConstraints' (list) — no SDK member; verify: CFn-only field or silent drop
  // UNMATCHED: 'PlacementStrategies' (list) — no SDK member; verify: CFn-only field or silent drop
  // UNMATCHED: 'PlatformVersion' (string) — no SDK member; verify: CFn-only field or silent drop
  // UNMATCHED: 'PropagateTags' (string) — no SDK member; verify: CFn-only field or silent drop
  // UNMATCHED: 'Role' (string) — no SDK member; verify: CFn-only field or silent drop
  // UNMATCHED: 'SchedulingStrategy' (string) — no SDK member; verify: CFn-only field or silent drop
  // UNMATCHED: 'ServiceConnectConfiguration' (structure) — no SDK member; verify: CFn-only field or silent drop
  // RENAME-CANDIDATE (NOT emitted; confirm via override table): 'ServiceName' -> 'service' (fuzzy-matched to "service" (overlap 0.64))
  // UNMATCHED: 'ServiceRegistries' (list) — no SDK member; verify: CFn-only field or silent drop
  // UNMATCHED: 'Tags' (list) — no SDK member; verify: CFn-only field or silent drop
  // UNMATCHED: 'TaskDefinition' (string) — no SDK member; verify: CFn-only field or silent drop
  // UNMATCHED: 'VolumeConfigurations' (list) — no SDK member; verify: CFn-only field or silent drop
  // UNMATCHED: 'VpcLatticeConfigurations' (list) — no SDK member; verify: CFn-only field or silent drop
  return out;
}

/** CreateService (handlers) — input shape CreateServiceRequest */
export function buildCreateInput(properties: Record<string, unknown>): Record<string, unknown> {
  return map_0(properties);
}

/** UpdateService (handlers) — input shape UpdateServiceRequest */
export function buildUpdateInput(properties: Record<string, unknown>): Record<string, unknown> {
  return map_36(properties);
}

/** DeleteService (handlers) — input shape DeleteServiceRequest */
export function buildDeleteInput(properties: Record<string, unknown>): Record<string, unknown> {
  return map_37(properties);
}

