// Generated by scripts/poc-codegen for AWS::CodeBuild::Project — DO NOT EDIT

// Source models: CFn registry schema + codebuild-2016-10-06.json

function toNum(v: unknown): number | undefined {
  if (v === undefined || v === null) return undefined;
  if (typeof v === 'number') return v;
  const n = Number(v);
  if (Number.isNaN(n)) throw new Error(`expected a number, got: ${JSON.stringify(v)}`);
  return n;
}
function toBool(v: unknown): boolean | undefined {
  if (v === undefined || v === null) return undefined;
  if (typeof v === 'boolean') return v;
  if (v === 'true' || v === 'True') return true;
  if (v === 'false' || v === 'False') return false;
  throw new Error(`expected a boolean, got: ${JSON.stringify(v)}`);
}
function toDateV(v: unknown): Date | undefined {
  if (v === undefined || v === null) return undefined;
  if (v instanceof Date) return v;
  const d = typeof v === 'string' || typeof v === 'number' ? new Date(v) : new Date(NaN);
  if (Number.isNaN(d.getTime())) throw new Error(`unparsable time value: ${JSON.stringify(v)}`);
  return d;
}
function toJsonString(v: unknown): string | undefined {
  if (v === undefined || v === null) return undefined;
  return typeof v === 'string' ? v : JSON.stringify(v);
}

// Artifacts -> ProjectArtifacts
function map_1(input: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  {
    const v = input['ArtifactIdentifier'];
    if (v !== undefined) out['artifactIdentifier'] = v;
  }
  {
    const v = input['EncryptionDisabled'];
    if (v !== undefined) out['encryptionDisabled'] = v;
  }
  {
    const v = input['Location'];
    if (v !== undefined) out['location'] = v;
  }
  {
    const v = input['Name'];
    if (v !== undefined) out['name'] = v;
  }
  {
    const v = input['NamespaceType'];
    if (v !== undefined) out['namespaceType'] = v;
  }
  {
    const v = input['OverrideArtifactName'];
    if (v !== undefined) out['overrideArtifactName'] = v;
  }
  {
    const v = input['Packaging'];
    if (v !== undefined) out['packaging'] = v;
  }
  {
    const v = input['Path'];
    if (v !== undefined) out['path'] = v;
  }
  {
    const v = input['Type'];
    if (v !== undefined) out['type'] = v;
  }
  return out;
}

// BatchRestrictions -> BatchRestrictions
function map_11(input: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  {
    const v = input['ComputeTypesAllowed'];
    if (v !== undefined) out['computeTypesAllowed'] = v;
  }
  {
    const v = input['MaximumBuildsAllowed'];
    if (v !== undefined) out['maximumBuildsAllowed'] = v;
  }
  return out;
}

// ProjectBuildBatchConfig -> ProjectBuildBatchConfig
function map_2(input: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  {
    const v = input['BatchReportMode'];
    if (v !== undefined) out['batchReportMode'] = v;
  }
  {
    const v = input['CombineArtifacts'];
    if (v !== undefined) out['combineArtifacts'] = v;
  }
  {
    const v = input['Restrictions'];
    if (v !== undefined) out['restrictions'] = map_11(v as Record<string, unknown>);
  }
  {
    const v = input['ServiceRole'];
    if (v !== undefined) out['serviceRole'] = v;
  }
  {
    const v = input['TimeoutInMins'];
    if (v !== undefined) out['timeoutInMins'] = v;
  }
  return out;
}

// ProjectCache -> ProjectCache
function map_3(input: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  {
    const v = input['CacheNamespace'];
    if (v !== undefined) out['cacheNamespace'] = v;
  }
  {
    const v = input['Location'];
    if (v !== undefined) out['location'] = v;
  }
  {
    const v = input['Modes'];
    if (v !== undefined) out['modes'] = v;
  }
  {
    const v = input['Type'];
    if (v !== undefined) out['type'] = v;
  }
  return out;
}

// DockerServer -> DockerServer
function map_12(input: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  {
    const v = input['ComputeType'];
    if (v !== undefined) out['computeType'] = v;
  }
  {
    const v = input['SecurityGroupIds'];
    if (v !== undefined) out['securityGroupIds'] = v;
  }
  return out;
}

// EnvironmentVariable -> EnvironmentVariable
function map_13(input: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  {
    const v = input['Name'];
    if (v !== undefined) out['name'] = v;
  }
  {
    const v = input['Type'];
    if (v !== undefined) out['type'] = v;
  }
  {
    const v = input['Value'];
    if (v !== undefined) out['value'] = v;
  }
  return out;
}

// ProjectFleet -> ProjectFleet
function map_14(input: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  {
    const v = input['FleetArn'];
    if (v !== undefined) out['fleetArn'] = v;
  }
  return out;
}

// RegistryCredential -> RegistryCredential
function map_15(input: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  {
    const v = input['Credential'];
    if (v !== undefined) out['credential'] = v;
  }
  {
    const v = input['CredentialProvider'];
    if (v !== undefined) out['credentialProvider'] = v;
  }
  return out;
}

// Environment -> ProjectEnvironment
function map_4(input: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  {
    const v = input['Certificate'];
    if (v !== undefined) out['certificate'] = v;
  }
  {
    const v = input['ComputeType'];
    if (v !== undefined) out['computeType'] = v;
  }
  {
    const v = input['DockerServer'];
    if (v !== undefined) out['dockerServer'] = map_12(v as Record<string, unknown>);
  }
  {
    const v = input['EnvironmentVariables'];
    if (v !== undefined) out['environmentVariables'] = (v as unknown[]).map((e) => map_13(e as Record<string, unknown>));
  }
  {
    const v = input['Fleet'];
    if (v !== undefined) out['fleet'] = map_14(v as Record<string, unknown>);
  }
  // VERSION-SKEW (NOT emitted): 'HostKernel' -> 'hostKernel' is absent from the installed SDK client; the serializer would silently drop it
  {
    const v = input['Image'];
    if (v !== undefined) out['image'] = v;
  }
  {
    const v = input['ImagePullCredentialsType'];
    if (v !== undefined) out['imagePullCredentialsType'] = v;
  }
  {
    const v = input['PrivilegedMode'];
    if (v !== undefined) out['privilegedMode'] = v;
  }
  {
    const v = input['RegistryCredential'];
    if (v !== undefined) out['registryCredential'] = map_15(v as Record<string, unknown>);
  }
  {
    const v = input['Type'];
    if (v !== undefined) out['type'] = v;
  }
  return out;
}

// ProjectFileSystemLocation -> ProjectFileSystemLocation
function map_5(input: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  {
    const v = input['Identifier'];
    if (v !== undefined) out['identifier'] = v;
  }
  {
    const v = input['Location'];
    if (v !== undefined) out['location'] = v;
  }
  {
    const v = input['MountOptions'];
    if (v !== undefined) out['mountOptions'] = v;
  }
  {
    const v = input['MountPoint'];
    if (v !== undefined) out['mountPoint'] = v;
  }
  {
    const v = input['Type'];
    if (v !== undefined) out['type'] = v;
  }
  return out;
}

// CloudWatchLogsConfig -> CloudWatchLogsConfig
function map_16(input: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  {
    const v = input['GroupName'];
    if (v !== undefined) out['groupName'] = v;
  }
  {
    const v = input['Status'];
    if (v !== undefined) out['status'] = v;
  }
  {
    const v = input['StreamName'];
    if (v !== undefined) out['streamName'] = v;
  }
  return out;
}

// S3LogsConfig -> S3LogsConfig
function map_17(input: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  {
    const v = input['EncryptionDisabled'];
    if (v !== undefined) out['encryptionDisabled'] = v;
  }
  {
    const v = input['Location'];
    if (v !== undefined) out['location'] = v;
  }
  {
    const v = input['Status'];
    if (v !== undefined) out['status'] = v;
  }
  return out;
}

// LogsConfig -> LogsConfig
function map_6(input: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  {
    const v = input['CloudWatchLogs'];
    if (v !== undefined) out['cloudWatchLogs'] = map_16(v as Record<string, unknown>);
  }
  {
    const v = input['S3Logs'];
    if (v !== undefined) out['s3Logs'] = map_17(v as Record<string, unknown>);
  }
  return out;
}

// ProjectSourceVersion -> ProjectSourceVersion
function map_7(input: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  {
    const v = input['SourceIdentifier'];
    if (v !== undefined) out['sourceIdentifier'] = v;
  }
  {
    const v = input['SourceVersion'];
    if (v !== undefined) out['sourceVersion'] = v;
  }
  return out;
}

// SourceAuth -> SourceAuth
function map_18(input: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  {
    const v = input['Resource'];
    if (v !== undefined) out['resource'] = v;
  }
  {
    const v = input['Type'];
    if (v !== undefined) out['type'] = v;
  }
  return out;
}

// BuildStatusConfig -> BuildStatusConfig
function map_19(input: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  {
    const v = input['Context'];
    if (v !== undefined) out['context'] = v;
  }
  {
    const v = input['TargetUrl'];
    if (v !== undefined) out['targetUrl'] = v;
  }
  return out;
}

// GitSubmodulesConfig -> GitSubmodulesConfig
function map_20(input: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  {
    const v = input['FetchSubmodules'];
    if (v !== undefined) out['fetchSubmodules'] = v;
  }
  return out;
}

// Source -> ProjectSource
function map_8(input: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  {
    const v = input['Auth'];
    if (v !== undefined) out['auth'] = map_18(v as Record<string, unknown>);
  }
  // case-divergence: 'BuildSpec' -> 'buildspec'
  {
    const v = input['BuildSpec'];
    if (v !== undefined) out['buildspec'] = v;
  }
  {
    const v = input['BuildStatusConfig'];
    if (v !== undefined) out['buildStatusConfig'] = map_19(v as Record<string, unknown>);
  }
  {
    const v = input['GitCloneDepth'];
    if (v !== undefined) out['gitCloneDepth'] = v;
  }
  {
    const v = input['GitSubmodulesConfig'];
    if (v !== undefined) out['gitSubmodulesConfig'] = map_20(v as Record<string, unknown>);
  }
  {
    const v = input['InsecureSsl'];
    if (v !== undefined) out['insecureSsl'] = v;
  }
  {
    const v = input['Location'];
    if (v !== undefined) out['location'] = v;
  }
  {
    const v = input['ReportBuildStatus'];
    if (v !== undefined) out['reportBuildStatus'] = v;
  }
  {
    const v = input['SourceIdentifier'];
    if (v !== undefined) out['sourceIdentifier'] = v;
  }
  {
    const v = input['Type'];
    if (v !== undefined) out['type'] = v;
  }
  return out;
}

// Tag -> Tag
function map_9(input: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  {
    const v = input['Key'];
    if (v !== undefined) out['key'] = v;
  }
  {
    const v = input['Value'];
    if (v !== undefined) out['value'] = v;
  }
  return out;
}

// VpcConfig -> VpcConfig
function map_10(input: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  {
    const v = input['SecurityGroupIds'];
    if (v !== undefined) out['securityGroupIds'] = v;
  }
  {
    const v = input['Subnets'];
    if (v !== undefined) out['subnets'] = v;
  }
  {
    const v = input['VpcId'];
    if (v !== undefined) out['vpcId'] = v;
  }
  return out;
}

// #top(CreateProject) -> CreateProjectInput
function map_0(input: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  {
    const v = input['Artifacts'];
    if (v !== undefined) out['artifacts'] = map_1(v as Record<string, unknown>);
  }
  {
    const v = input['AutoRetryLimit'];
    if (v !== undefined) out['autoRetryLimit'] = v;
  }
  {
    const v = input['BadgeEnabled'];
    if (v !== undefined) out['badgeEnabled'] = v;
  }
  {
    const v = input['BuildBatchConfig'];
    if (v !== undefined) out['buildBatchConfig'] = map_2(v as Record<string, unknown>);
  }
  {
    const v = input['Cache'];
    if (v !== undefined) out['cache'] = map_3(v as Record<string, unknown>);
  }
  {
    const v = input['ConcurrentBuildLimit'];
    if (v !== undefined) out['concurrentBuildLimit'] = v;
  }
  {
    const v = input['Description'];
    if (v !== undefined) out['description'] = v;
  }
  {
    const v = input['EncryptionKey'];
    if (v !== undefined) out['encryptionKey'] = v;
  }
  {
    const v = input['Environment'];
    if (v !== undefined) out['environment'] = map_4(v as Record<string, unknown>);
  }
  {
    const v = input['FileSystemLocations'];
    if (v !== undefined) out['fileSystemLocations'] = (v as unknown[]).map((e) => map_5(e as Record<string, unknown>));
  }
  {
    const v = input['LogsConfig'];
    if (v !== undefined) out['logsConfig'] = map_6(v as Record<string, unknown>);
  }
  {
    const v = input['Name'];
    if (v !== undefined) out['name'] = v;
  }
  {
    const v = input['QueuedTimeoutInMinutes'];
    if (v !== undefined) out['queuedTimeoutInMinutes'] = v;
  }
  // UNMATCHED: 'ResourceAccessRole' (string) — no SDK member; verify: CFn-only field or silent drop
  {
    const v = input['SecondaryArtifacts'];
    if (v !== undefined) out['secondaryArtifacts'] = (v as unknown[]).map((e) => map_1(e as Record<string, unknown>));
  }
  {
    const v = input['SecondarySourceVersions'];
    if (v !== undefined) out['secondarySourceVersions'] = (v as unknown[]).map((e) => map_7(e as Record<string, unknown>));
  }
  {
    const v = input['SecondarySources'];
    if (v !== undefined) out['secondarySources'] = (v as unknown[]).map((e) => map_8(e as Record<string, unknown>));
  }
  {
    const v = input['ServiceRole'];
    if (v !== undefined) out['serviceRole'] = v;
  }
  {
    const v = input['Source'];
    if (v !== undefined) out['source'] = map_8(v as Record<string, unknown>);
  }
  {
    const v = input['SourceVersion'];
    if (v !== undefined) out['sourceVersion'] = v;
  }
  {
    const v = input['Tags'];
    if (v !== undefined) out['tags'] = (v as unknown[]).map((e) => map_9(e as Record<string, unknown>));
  }
  {
    const v = input['TimeoutInMinutes'];
    if (v !== undefined) out['timeoutInMinutes'] = v;
  }
  // UNMATCHED: 'Triggers' (structure) — no SDK member; verify: CFn-only field or silent drop
  // UNMATCHED: 'Visibility' (string) — no SDK member; verify: CFn-only field or silent drop
  {
    const v = input['VpcConfig'];
    if (v !== undefined) out['vpcConfig'] = map_10(v as Record<string, unknown>);
  }
  return out;
}

// #top(UpdateProject) -> UpdateProjectInput
function map_21(input: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  {
    const v = input['Artifacts'];
    if (v !== undefined) out['artifacts'] = map_1(v as Record<string, unknown>);
  }
  {
    const v = input['AutoRetryLimit'];
    if (v !== undefined) out['autoRetryLimit'] = v;
  }
  {
    const v = input['BadgeEnabled'];
    if (v !== undefined) out['badgeEnabled'] = v;
  }
  {
    const v = input['BuildBatchConfig'];
    if (v !== undefined) out['buildBatchConfig'] = map_2(v as Record<string, unknown>);
  }
  {
    const v = input['Cache'];
    if (v !== undefined) out['cache'] = map_3(v as Record<string, unknown>);
  }
  {
    const v = input['ConcurrentBuildLimit'];
    if (v !== undefined) out['concurrentBuildLimit'] = v;
  }
  {
    const v = input['Description'];
    if (v !== undefined) out['description'] = v;
  }
  {
    const v = input['EncryptionKey'];
    if (v !== undefined) out['encryptionKey'] = v;
  }
  {
    const v = input['Environment'];
    if (v !== undefined) out['environment'] = map_4(v as Record<string, unknown>);
  }
  {
    const v = input['FileSystemLocations'];
    if (v !== undefined) out['fileSystemLocations'] = (v as unknown[]).map((e) => map_5(e as Record<string, unknown>));
  }
  {
    const v = input['LogsConfig'];
    if (v !== undefined) out['logsConfig'] = map_6(v as Record<string, unknown>);
  }
  {
    const v = input['Name'];
    if (v !== undefined) out['name'] = v;
  }
  {
    const v = input['QueuedTimeoutInMinutes'];
    if (v !== undefined) out['queuedTimeoutInMinutes'] = v;
  }
  // UNMATCHED: 'ResourceAccessRole' (string) — no SDK member; verify: CFn-only field or silent drop
  {
    const v = input['SecondaryArtifacts'];
    if (v !== undefined) out['secondaryArtifacts'] = (v as unknown[]).map((e) => map_1(e as Record<string, unknown>));
  }
  {
    const v = input['SecondarySourceVersions'];
    if (v !== undefined) out['secondarySourceVersions'] = (v as unknown[]).map((e) => map_7(e as Record<string, unknown>));
  }
  {
    const v = input['SecondarySources'];
    if (v !== undefined) out['secondarySources'] = (v as unknown[]).map((e) => map_8(e as Record<string, unknown>));
  }
  {
    const v = input['ServiceRole'];
    if (v !== undefined) out['serviceRole'] = v;
  }
  {
    const v = input['Source'];
    if (v !== undefined) out['source'] = map_8(v as Record<string, unknown>);
  }
  {
    const v = input['SourceVersion'];
    if (v !== undefined) out['sourceVersion'] = v;
  }
  {
    const v = input['Tags'];
    if (v !== undefined) out['tags'] = (v as unknown[]).map((e) => map_9(e as Record<string, unknown>));
  }
  {
    const v = input['TimeoutInMinutes'];
    if (v !== undefined) out['timeoutInMinutes'] = v;
  }
  // UNMATCHED: 'Triggers' (structure) — no SDK member; verify: CFn-only field or silent drop
  // UNMATCHED: 'Visibility' (string) — no SDK member; verify: CFn-only field or silent drop
  {
    const v = input['VpcConfig'];
    if (v !== undefined) out['vpcConfig'] = map_10(v as Record<string, unknown>);
  }
  return out;
}

// #top(DeleteProject) -> DeleteProjectInput
function map_22(input: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  // UNMATCHED: 'Artifacts' (structure) — no SDK member; verify: CFn-only field or silent drop
  // UNMATCHED: 'AutoRetryLimit' (number) — no SDK member; verify: CFn-only field or silent drop
  // UNMATCHED: 'BadgeEnabled' (boolean) — no SDK member; verify: CFn-only field or silent drop
  // UNMATCHED: 'BuildBatchConfig' (structure) — no SDK member; verify: CFn-only field or silent drop
  // UNMATCHED: 'Cache' (structure) — no SDK member; verify: CFn-only field or silent drop
  // UNMATCHED: 'ConcurrentBuildLimit' (number) — no SDK member; verify: CFn-only field or silent drop
  // UNMATCHED: 'Description' (string) — no SDK member; verify: CFn-only field or silent drop
  // UNMATCHED: 'EncryptionKey' (string) — no SDK member; verify: CFn-only field or silent drop
  // UNMATCHED: 'Environment' (structure) — no SDK member; verify: CFn-only field or silent drop
  // UNMATCHED: 'FileSystemLocations' (list) — no SDK member; verify: CFn-only field or silent drop
  // UNMATCHED: 'LogsConfig' (structure) — no SDK member; verify: CFn-only field or silent drop
  {
    const v = input['Name'];
    if (v !== undefined) out['name'] = v;
  }
  // UNMATCHED: 'QueuedTimeoutInMinutes' (number) — no SDK member; verify: CFn-only field or silent drop
  // UNMATCHED: 'ResourceAccessRole' (string) — no SDK member; verify: CFn-only field or silent drop
  // UNMATCHED: 'SecondaryArtifacts' (list) — no SDK member; verify: CFn-only field or silent drop
  // UNMATCHED: 'SecondarySourceVersions' (list) — no SDK member; verify: CFn-only field or silent drop
  // UNMATCHED: 'SecondarySources' (list) — no SDK member; verify: CFn-only field or silent drop
  // UNMATCHED: 'ServiceRole' (string) — no SDK member; verify: CFn-only field or silent drop
  // UNMATCHED: 'Source' (structure) — no SDK member; verify: CFn-only field or silent drop
  // UNMATCHED: 'SourceVersion' (string) — no SDK member; verify: CFn-only field or silent drop
  // UNMATCHED: 'Tags' (list) — no SDK member; verify: CFn-only field or silent drop
  // UNMATCHED: 'TimeoutInMinutes' (number) — no SDK member; verify: CFn-only field or silent drop
  // UNMATCHED: 'Triggers' (structure) — no SDK member; verify: CFn-only field or silent drop
  // UNMATCHED: 'Visibility' (string) — no SDK member; verify: CFn-only field or silent drop
  // UNMATCHED: 'VpcConfig' (structure) — no SDK member; verify: CFn-only field or silent drop
  return out;
}

/** CreateProject (verb-heuristic) — input shape CreateProjectInput */
export function buildCreateInput(properties: Record<string, unknown>): Record<string, unknown> {
  return map_0(properties);
}

/** UpdateProject (verb-heuristic) — input shape UpdateProjectInput */
export function buildUpdateInput(properties: Record<string, unknown>): Record<string, unknown> {
  return map_21(properties);
}

/** DeleteProject (verb-heuristic) — input shape DeleteProjectInput */
export function buildDeleteInput(properties: Record<string, unknown>): Record<string, unknown> {
  return map_22(properties);
}

