// Generated by scripts/poc-codegen for AWS::CloudFront::Distribution — DO NOT EDIT

// Source models: CFn registry schema + cloudfront-2020-05-31.json

function toNum(v: unknown): number | undefined {
  if (v === undefined || v === null) return undefined;
  if (typeof v === 'number') return v;
  const n = Number(v);
  if (Number.isNaN(n)) throw new Error(`expected a number, got: ${JSON.stringify(v)}`);
  return n;
}
function toBool(v: unknown): boolean | undefined {
  if (v === undefined || v === null) return undefined;
  if (typeof v === 'boolean') return v;
  if (v === 'true') return true;
  if (v === 'false') return false;
  throw new Error(`expected a boolean, got: ${JSON.stringify(v)}`);
}
function toDateV(v: unknown): Date | undefined {
  if (v === undefined || v === null) return undefined;
  if (v instanceof Date) return v;
  const d = typeof v === 'string' || typeof v === 'number' ? new Date(v) : new Date(NaN);
  if (Number.isNaN(d.getTime())) throw new Error(`unparsable time value: ${JSON.stringify(v)}`);
  return d;
}
function toJsonString(v: unknown): string | undefined {
  if (v === undefined || v === null) return undefined;
  return typeof v === 'string' ? v : JSON.stringify(v);
}

// Cookies -> CookiePreference
function map_18(input: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  {
    const v = input['Forward'];
    if (v !== undefined) out['Forward'] = v;
  }
  {
    const v = input['WhitelistedNames'];
    if (v !== undefined) out['WhitelistedNames'] = { Quantity: (v as unknown[]).length, Items: v };
  }
  return out;
}

// ForwardedValues -> ForwardedValues
function map_14(input: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  {
    const v = input['Cookies'];
    if (v !== undefined) out['Cookies'] = map_18(v as Record<string, unknown>);
  }
  {
    const v = input['Headers'];
    if (v !== undefined) out['Headers'] = { Quantity: (v as unknown[]).length, Items: v };
  }
  {
    const v = input['QueryString'];
    if (v !== undefined) out['QueryString'] = v;
  }
  {
    const v = input['QueryStringCacheKeys'];
    if (v !== undefined) out['QueryStringCacheKeys'] = { Quantity: (v as unknown[]).length, Items: v };
  }
  return out;
}

// FunctionAssociation -> FunctionAssociation
function map_15(input: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  {
    const v = input['EventType'];
    if (v !== undefined) out['EventType'] = v;
  }
  {
    const v = input['FunctionARN'];
    if (v !== undefined) out['FunctionARN'] = v;
  }
  return out;
}

// GrpcConfig -> GrpcConfig
function map_16(input: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  {
    const v = input['Enabled'];
    if (v !== undefined) out['Enabled'] = v;
  }
  return out;
}

// LambdaFunctionAssociation -> LambdaFunctionAssociation
function map_17(input: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  {
    const v = input['EventType'];
    if (v !== undefined) out['EventType'] = v;
  }
  {
    const v = input['IncludeBody'];
    if (v !== undefined) out['IncludeBody'] = v;
  }
  {
    const v = input['LambdaFunctionARN'];
    if (v !== undefined) out['LambdaFunctionARN'] = v;
  }
  return out;
}

// CacheBehavior -> CacheBehavior
function map_2(input: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  {
    const v = input['AllowedMethods'];
    if (v !== undefined) out['AllowedMethods'] = { Quantity: (v as unknown[]).length, Items: v };
  }
  {
    const v = input['CachePolicyId'];
    if (v !== undefined) out['CachePolicyId'] = v;
  }
  // UNMATCHED: 'CachedMethods' (list) — no SDK member; verify: CFn-only field or silent drop
  {
    const v = input['Compress'];
    if (v !== undefined) out['Compress'] = v;
  }
  {
    const v = input['DefaultTTL'];
    if (v !== undefined) out['DefaultTTL'] = v;
  }
  {
    const v = input['FieldLevelEncryptionId'];
    if (v !== undefined) out['FieldLevelEncryptionId'] = v;
  }
  {
    const v = input['ForwardedValues'];
    if (v !== undefined) out['ForwardedValues'] = map_14(v as Record<string, unknown>);
  }
  {
    const v = input['FunctionAssociations'];
    if (v !== undefined) out['FunctionAssociations'] = { Quantity: (v as unknown[]).length, Items: (v as unknown[]).map((e) => map_15(e as Record<string, unknown>)) };
  }
  {
    const v = input['GrpcConfig'];
    if (v !== undefined) out['GrpcConfig'] = map_16(v as Record<string, unknown>);
  }
  {
    const v = input['LambdaFunctionAssociations'];
    if (v !== undefined) out['LambdaFunctionAssociations'] = { Quantity: (v as unknown[]).length, Items: (v as unknown[]).map((e) => map_17(e as Record<string, unknown>)) };
  }
  {
    const v = input['MaxTTL'];
    if (v !== undefined) out['MaxTTL'] = v;
  }
  {
    const v = input['MinTTL'];
    if (v !== undefined) out['MinTTL'] = v;
  }
  {
    const v = input['OriginRequestPolicyId'];
    if (v !== undefined) out['OriginRequestPolicyId'] = v;
  }
  {
    const v = input['PathPattern'];
    if (v !== undefined) out['PathPattern'] = v;
  }
  {
    const v = input['RealtimeLogConfigArn'];
    if (v !== undefined) out['RealtimeLogConfigArn'] = v;
  }
  {
    const v = input['ResponseHeadersPolicyId'];
    if (v !== undefined) out['ResponseHeadersPolicyId'] = v;
  }
  {
    const v = input['SmoothStreaming'];
    if (v !== undefined) out['SmoothStreaming'] = v;
  }
  {
    const v = input['TargetOriginId'];
    if (v !== undefined) out['TargetOriginId'] = v;
  }
  {
    const v = input['TrustedKeyGroups'];
    if (v !== undefined) out['TrustedKeyGroups'] = { Quantity: (v as unknown[]).length, Items: v };
  }
  {
    const v = input['TrustedSigners'];
    if (v !== undefined) out['TrustedSigners'] = { Quantity: (v as unknown[]).length, Items: v };
  }
  {
    const v = input['ViewerProtocolPolicy'];
    if (v !== undefined) out['ViewerProtocolPolicy'] = v;
  }
  return out;
}

// CacheTagConfig -> CacheTagConfig
function map_3(input: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  {
    const v = input['HeaderName'];
    if (v !== undefined) out['HeaderName'] = v;
  }
  return out;
}

// ConnectionFunctionAssociation -> ConnectionFunctionAssociation
function map_4(input: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  {
    const v = input['Id'];
    if (v !== undefined) out['Id'] = v;
  }
  return out;
}

// CustomErrorResponse -> CustomErrorResponse
function map_5(input: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  {
    const v = input['ErrorCachingMinTTL'];
    if (v !== undefined) out['ErrorCachingMinTTL'] = v;
  }
  {
    const v = input['ErrorCode'];
    if (v !== undefined) out['ErrorCode'] = v;
  }
  {
    const v = input['ResponseCode'];
    if (v !== undefined) out['ResponseCode'] = String(v);
  }
  {
    const v = input['ResponsePagePath'];
    if (v !== undefined) out['ResponsePagePath'] = v;
  }
  return out;
}

// DefaultCacheBehavior -> DefaultCacheBehavior
function map_6(input: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  {
    const v = input['AllowedMethods'];
    if (v !== undefined) out['AllowedMethods'] = { Quantity: (v as unknown[]).length, Items: v };
  }
  {
    const v = input['CachePolicyId'];
    if (v !== undefined) out['CachePolicyId'] = v;
  }
  // UNMATCHED: 'CachedMethods' (list) — no SDK member; verify: CFn-only field or silent drop
  {
    const v = input['Compress'];
    if (v !== undefined) out['Compress'] = v;
  }
  {
    const v = input['DefaultTTL'];
    if (v !== undefined) out['DefaultTTL'] = v;
  }
  {
    const v = input['FieldLevelEncryptionId'];
    if (v !== undefined) out['FieldLevelEncryptionId'] = v;
  }
  {
    const v = input['ForwardedValues'];
    if (v !== undefined) out['ForwardedValues'] = map_14(v as Record<string, unknown>);
  }
  {
    const v = input['FunctionAssociations'];
    if (v !== undefined) out['FunctionAssociations'] = { Quantity: (v as unknown[]).length, Items: (v as unknown[]).map((e) => map_15(e as Record<string, unknown>)) };
  }
  {
    const v = input['GrpcConfig'];
    if (v !== undefined) out['GrpcConfig'] = map_16(v as Record<string, unknown>);
  }
  {
    const v = input['LambdaFunctionAssociations'];
    if (v !== undefined) out['LambdaFunctionAssociations'] = { Quantity: (v as unknown[]).length, Items: (v as unknown[]).map((e) => map_17(e as Record<string, unknown>)) };
  }
  {
    const v = input['MaxTTL'];
    if (v !== undefined) out['MaxTTL'] = v;
  }
  {
    const v = input['MinTTL'];
    if (v !== undefined) out['MinTTL'] = v;
  }
  {
    const v = input['OriginRequestPolicyId'];
    if (v !== undefined) out['OriginRequestPolicyId'] = v;
  }
  {
    const v = input['RealtimeLogConfigArn'];
    if (v !== undefined) out['RealtimeLogConfigArn'] = v;
  }
  {
    const v = input['ResponseHeadersPolicyId'];
    if (v !== undefined) out['ResponseHeadersPolicyId'] = v;
  }
  {
    const v = input['SmoothStreaming'];
    if (v !== undefined) out['SmoothStreaming'] = v;
  }
  {
    const v = input['TargetOriginId'];
    if (v !== undefined) out['TargetOriginId'] = v;
  }
  {
    const v = input['TrustedKeyGroups'];
    if (v !== undefined) out['TrustedKeyGroups'] = { Quantity: (v as unknown[]).length, Items: v };
  }
  {
    const v = input['TrustedSigners'];
    if (v !== undefined) out['TrustedSigners'] = { Quantity: (v as unknown[]).length, Items: v };
  }
  {
    const v = input['ViewerProtocolPolicy'];
    if (v !== undefined) out['ViewerProtocolPolicy'] = v;
  }
  return out;
}

// Logging -> LoggingConfig
function map_7(input: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  {
    const v = input['Bucket'];
    if (v !== undefined) out['Bucket'] = v;
  }
  {
    const v = input['IncludeCookies'];
    if (v !== undefined) out['IncludeCookies'] = v;
  }
  {
    const v = input['Prefix'];
    if (v !== undefined) out['Prefix'] = v;
  }
  return out;
}

// StatusCodes -> StatusCodes
function map_22(input: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  {
    const v = input['Items'];
    if (v !== undefined) out['Items'] = v;
  }
  {
    const v = input['Quantity'];
    if (v !== undefined) out['Quantity'] = v;
  }
  return out;
}

// OriginGroupFailoverCriteria -> OriginGroupFailoverCriteria
function map_20(input: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  {
    const v = input['StatusCodes'];
    if (v !== undefined) out['StatusCodes'] = map_22(v as Record<string, unknown>);
  }
  return out;
}

// OriginGroupMember -> OriginGroupMember
function map_23(input: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  {
    const v = input['OriginId'];
    if (v !== undefined) out['OriginId'] = v;
  }
  return out;
}

// OriginGroupMembers -> OriginGroupMembers
function map_21(input: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  {
    const v = input['Items'];
    if (v !== undefined) out['Items'] = (v as unknown[]).map((e) => map_23(e as Record<string, unknown>));
  }
  {
    const v = input['Quantity'];
    if (v !== undefined) out['Quantity'] = v;
  }
  return out;
}

// OriginGroup -> OriginGroup
function map_19(input: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  {
    const v = input['FailoverCriteria'];
    if (v !== undefined) out['FailoverCriteria'] = map_20(v as Record<string, unknown>);
  }
  {
    const v = input['Id'];
    if (v !== undefined) out['Id'] = v;
  }
  {
    const v = input['Members'];
    if (v !== undefined) out['Members'] = map_21(v as Record<string, unknown>);
  }
  {
    const v = input['SelectionCriteria'];
    if (v !== undefined) out['SelectionCriteria'] = v;
  }
  return out;
}

// OriginGroups -> OriginGroups
function map_8(input: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  {
    const v = input['Items'];
    if (v !== undefined) out['Items'] = (v as unknown[]).map((e) => map_19(e as Record<string, unknown>));
  }
  {
    const v = input['Quantity'];
    if (v !== undefined) out['Quantity'] = v;
  }
  return out;
}

// OriginMtlsConfig -> OriginMtlsConfig
function map_29(input: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  {
    const v = input['ClientCertificateArn'];
    if (v !== undefined) out['ClientCertificateArn'] = v;
  }
  return out;
}

// CustomOriginConfig -> CustomOriginConfig
function map_24(input: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  {
    const v = input['HTTPPort'];
    if (v !== undefined) out['HTTPPort'] = v;
  }
  {
    const v = input['HTTPSPort'];
    if (v !== undefined) out['HTTPSPort'] = v;
  }
  {
    const v = input['IpAddressType'];
    if (v !== undefined) out['IpAddressType'] = v;
  }
  {
    const v = input['OriginKeepaliveTimeout'];
    if (v !== undefined) out['OriginKeepaliveTimeout'] = v;
  }
  {
    const v = input['OriginMtlsConfig'];
    if (v !== undefined) out['OriginMtlsConfig'] = map_29(v as Record<string, unknown>);
  }
  {
    const v = input['OriginProtocolPolicy'];
    if (v !== undefined) out['OriginProtocolPolicy'] = v;
  }
  {
    const v = input['OriginReadTimeout'];
    if (v !== undefined) out['OriginReadTimeout'] = v;
  }
  // case-divergence: 'OriginSSLProtocols' -> 'OriginSslProtocols'
  {
    const v = input['OriginSSLProtocols'];
    if (v !== undefined) out['OriginSslProtocols'] = { Quantity: (v as unknown[]).length, Items: v };
  }
  return out;
}

// OriginCustomHeader -> OriginCustomHeader
function map_25(input: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  {
    const v = input['HeaderName'];
    if (v !== undefined) out['HeaderName'] = v;
  }
  {
    const v = input['HeaderValue'];
    if (v !== undefined) out['HeaderValue'] = v;
  }
  return out;
}

// OriginShield -> OriginShield
function map_26(input: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  {
    const v = input['Enabled'];
    if (v !== undefined) out['Enabled'] = v;
  }
  {
    const v = input['OriginShieldRegion'];
    if (v !== undefined) out['OriginShieldRegion'] = v;
  }
  return out;
}

// S3OriginConfig -> S3OriginConfig
function map_27(input: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  {
    const v = input['OriginAccessIdentity'];
    if (v !== undefined) out['OriginAccessIdentity'] = v;
  }
  {
    const v = input['OriginReadTimeout'];
    if (v !== undefined) out['OriginReadTimeout'] = v;
  }
  return out;
}

// VpcOriginConfig -> VpcOriginConfig
function map_28(input: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  {
    const v = input['OriginKeepaliveTimeout'];
    if (v !== undefined) out['OriginKeepaliveTimeout'] = v;
  }
  {
    const v = input['OriginReadTimeout'];
    if (v !== undefined) out['OriginReadTimeout'] = v;
  }
  {
    const v = input['OwnerAccountId'];
    if (v !== undefined) out['OwnerAccountId'] = v;
  }
  {
    const v = input['VpcOriginId'];
    if (v !== undefined) out['VpcOriginId'] = v;
  }
  return out;
}

// Origin -> Origin
function map_9(input: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  {
    const v = input['ConnectionAttempts'];
    if (v !== undefined) out['ConnectionAttempts'] = v;
  }
  {
    const v = input['ConnectionTimeout'];
    if (v !== undefined) out['ConnectionTimeout'] = v;
  }
  {
    const v = input['CustomOriginConfig'];
    if (v !== undefined) out['CustomOriginConfig'] = map_24(v as Record<string, unknown>);
  }
  {
    const v = input['DomainName'];
    if (v !== undefined) out['DomainName'] = v;
  }
  {
    const v = input['Id'];
    if (v !== undefined) out['Id'] = v;
  }
  {
    const v = input['OriginAccessControlId'];
    if (v !== undefined) out['OriginAccessControlId'] = v;
  }
  // RENAME-CANDIDATE (confirm): 'OriginCustomHeaders' -> 'CustomHeaders'
  // fuzzy-matched to "CustomHeaders" (overlap 0.68)
  {
    const v = input['OriginCustomHeaders'];
    if (v !== undefined) out['CustomHeaders'] = { Quantity: (v as unknown[]).length, Items: (v as unknown[]).map((e) => map_25(e as Record<string, unknown>)) };
  }
  {
    const v = input['OriginPath'];
    if (v !== undefined) out['OriginPath'] = v;
  }
  {
    const v = input['OriginShield'];
    if (v !== undefined) out['OriginShield'] = map_26(v as Record<string, unknown>);
  }
  {
    const v = input['ResponseCompletionTimeout'];
    if (v !== undefined) out['ResponseCompletionTimeout'] = v;
  }
  {
    const v = input['S3OriginConfig'];
    if (v !== undefined) out['S3OriginConfig'] = map_27(v as Record<string, unknown>);
  }
  {
    const v = input['VpcOriginConfig'];
    if (v !== undefined) out['VpcOriginConfig'] = map_28(v as Record<string, unknown>);
  }
  return out;
}

// GeoRestriction -> GeoRestriction
function map_30(input: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  // UNMATCHED: 'Locations' (list) — no SDK member; verify: CFn-only field or silent drop
  {
    const v = input['RestrictionType'];
    if (v !== undefined) out['RestrictionType'] = v;
  }
  // TODO(required): SDK member 'Quantity' has no CFn source — synthesize it
  return out;
}

// Restrictions -> Restrictions
function map_10(input: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  {
    const v = input['GeoRestriction'];
    if (v !== undefined) out['GeoRestriction'] = map_30(v as Record<string, unknown>);
  }
  return out;
}

// ParameterDefinition.Definition.StringSchema -> StringSchemaConfig
function map_33(input: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  {
    const v = input['Comment'];
    if (v !== undefined) out['Comment'] = v;
  }
  {
    const v = input['DefaultValue'];
    if (v !== undefined) out['DefaultValue'] = v;
  }
  {
    const v = input['Required'];
    if (v !== undefined) out['Required'] = v;
  }
  return out;
}

// ParameterDefinition.Definition -> ParameterDefinitionSchema
function map_32(input: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  {
    const v = input['StringSchema'];
    if (v !== undefined) out['StringSchema'] = map_33(v as Record<string, unknown>);
  }
  return out;
}

// ParameterDefinition -> ParameterDefinition
function map_31(input: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  {
    const v = input['Definition'];
    if (v !== undefined) out['Definition'] = map_32(v as Record<string, unknown>);
  }
  {
    const v = input['Name'];
    if (v !== undefined) out['Name'] = v;
  }
  return out;
}

// DistributionConfig.TenantConfig -> TenantConfig
function map_11(input: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  {
    const v = input['ParameterDefinitions'];
    if (v !== undefined) out['ParameterDefinitions'] = (v as unknown[]).map((e) => map_31(e as Record<string, unknown>));
  }
  return out;
}

// ViewerCertificate -> ViewerCertificate
function map_12(input: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  // case-divergence: 'AcmCertificateArn' -> 'ACMCertificateArn'
  {
    const v = input['AcmCertificateArn'];
    if (v !== undefined) out['ACMCertificateArn'] = v;
  }
  {
    const v = input['CloudFrontDefaultCertificate'];
    if (v !== undefined) out['CloudFrontDefaultCertificate'] = v;
  }
  // case-divergence: 'IamCertificateId' -> 'IAMCertificateId'
  {
    const v = input['IamCertificateId'];
    if (v !== undefined) out['IAMCertificateId'] = v;
  }
  {
    const v = input['MinimumProtocolVersion'];
    if (v !== undefined) out['MinimumProtocolVersion'] = v;
  }
  // case-divergence: 'SslSupportMethod' -> 'SSLSupportMethod'
  {
    const v = input['SslSupportMethod'];
    if (v !== undefined) out['SSLSupportMethod'] = v;
  }
  return out;
}

// TrustStoreConfig -> TrustStoreConfig
function map_34(input: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  {
    const v = input['AdvertiseTrustStoreCaNames'];
    if (v !== undefined) out['AdvertiseTrustStoreCaNames'] = v;
  }
  {
    const v = input['IgnoreCertificateExpiry'];
    if (v !== undefined) out['IgnoreCertificateExpiry'] = v;
  }
  {
    const v = input['TrustStoreId'];
    if (v !== undefined) out['TrustStoreId'] = v;
  }
  return out;
}

// ViewerMtlsConfig -> ViewerMtlsConfig
function map_13(input: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  {
    const v = input['Mode'];
    if (v !== undefined) out['Mode'] = v;
  }
  {
    const v = input['TrustStoreConfig'];
    if (v !== undefined) out['TrustStoreConfig'] = map_34(v as Record<string, unknown>);
  }
  return out;
}

// DistributionConfig -> DistributionConfig
function map_1(input: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  {
    const v = input['Aliases'];
    if (v !== undefined) out['Aliases'] = { Quantity: (v as unknown[]).length, Items: v };
  }
  {
    const v = input['AnycastIpListId'];
    if (v !== undefined) out['AnycastIpListId'] = v;
  }
  // UNMATCHED: 'CNAMEs' (list) — no SDK member; verify: CFn-only field or silent drop
  {
    const v = input['CacheBehaviors'];
    if (v !== undefined) out['CacheBehaviors'] = { Quantity: (v as unknown[]).length, Items: (v as unknown[]).map((e) => map_2(e as Record<string, unknown>)) };
  }
  {
    const v = input['CacheTagConfig'];
    if (v !== undefined) out['CacheTagConfig'] = map_3(v as Record<string, unknown>);
  }
  {
    const v = input['Comment'];
    if (v !== undefined) out['Comment'] = v;
  }
  {
    const v = input['ConnectionFunctionAssociation'];
    if (v !== undefined) out['ConnectionFunctionAssociation'] = map_4(v as Record<string, unknown>);
  }
  {
    const v = input['ConnectionMode'];
    if (v !== undefined) out['ConnectionMode'] = v;
  }
  {
    const v = input['ContinuousDeploymentPolicyId'];
    if (v !== undefined) out['ContinuousDeploymentPolicyId'] = v;
  }
  {
    const v = input['CustomErrorResponses'];
    if (v !== undefined) out['CustomErrorResponses'] = { Quantity: (v as unknown[]).length, Items: (v as unknown[]).map((e) => map_5(e as Record<string, unknown>)) };
  }
  // UNMATCHED: 'CustomOrigin' (structure) — no SDK member; verify: CFn-only field or silent drop
  {
    const v = input['DefaultCacheBehavior'];
    if (v !== undefined) out['DefaultCacheBehavior'] = map_6(v as Record<string, unknown>);
  }
  {
    const v = input['DefaultRootObject'];
    if (v !== undefined) out['DefaultRootObject'] = v;
  }
  {
    const v = input['Enabled'];
    if (v !== undefined) out['Enabled'] = v;
  }
  {
    const v = input['HttpVersion'];
    if (v !== undefined) out['HttpVersion'] = v;
  }
  // RENAME-CANDIDATE (confirm): 'IPV6Enabled' -> 'IsIPV6Enabled'
  // fuzzy-matched to "IsIPV6Enabled" (overlap 0.85)
  {
    const v = input['IPV6Enabled'];
    if (v !== undefined) out['IsIPV6Enabled'] = v;
  }
  {
    const v = input['Logging'];
    if (v !== undefined) out['Logging'] = map_7(v as Record<string, unknown>);
  }
  {
    const v = input['OriginGroups'];
    if (v !== undefined) out['OriginGroups'] = map_8(v as Record<string, unknown>);
  }
  {
    const v = input['Origins'];
    if (v !== undefined) out['Origins'] = { Quantity: (v as unknown[]).length, Items: (v as unknown[]).map((e) => map_9(e as Record<string, unknown>)) };
    else out['Origins'] = { Quantity: 0, Items: [] }; // required wrapper: empty default
  }
  {
    const v = input['PriceClass'];
    if (v !== undefined) out['PriceClass'] = v;
  }
  {
    const v = input['Restrictions'];
    if (v !== undefined) out['Restrictions'] = map_10(v as Record<string, unknown>);
  }
  // UNMATCHED: 'S3Origin' (structure) — no SDK member; verify: CFn-only field or silent drop
  {
    const v = input['Staging'];
    if (v !== undefined) out['Staging'] = v;
  }
  {
    const v = input['TenantConfig'];
    if (v !== undefined) out['TenantConfig'] = map_11(v as Record<string, unknown>);
  }
  {
    const v = input['ViewerCertificate'];
    if (v !== undefined) out['ViewerCertificate'] = map_12(v as Record<string, unknown>);
  }
  {
    const v = input['ViewerMtlsConfig'];
    if (v !== undefined) out['ViewerMtlsConfig'] = map_13(v as Record<string, unknown>);
  }
  {
    const v = input['WebACLId'];
    if (v !== undefined) out['WebACLId'] = v;
  }
  // TODO(required): SDK member 'CallerReference' has no CFn source — synthesize it
  return out;
}

// #top(CreateDistribution) -> CreateDistributionRequest
function map_0(input: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  {
    const v = input['DistributionConfig'];
    if (v !== undefined) out['DistributionConfig'] = map_1(v as Record<string, unknown>);
  }
  // UNMATCHED: 'Tags' (list) — no SDK member; verify: CFn-only field or silent drop
  return out;
}

// #top(UpdateDistribution) -> UpdateDistributionRequest
function map_35(input: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  {
    const v = input['DistributionConfig'];
    if (v !== undefined) out['DistributionConfig'] = map_1(v as Record<string, unknown>);
  }
  // UNMATCHED: 'Tags' (list) — no SDK member; verify: CFn-only field or silent drop
  // TODO(required): SDK member 'Id' has no CFn source — synthesize it
  return out;
}

// #top(DeleteDistribution) -> DeleteDistributionRequest
function map_36(input: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  // UNMATCHED: 'DistributionConfig' (structure) — no SDK member; verify: CFn-only field or silent drop
  // UNMATCHED: 'Tags' (list) — no SDK member; verify: CFn-only field or silent drop
  // TODO(required): SDK member 'Id' has no CFn source — synthesize it
  return out;
}

/** CreateDistribution (handlers) — input shape CreateDistributionRequest */
export function buildCreateInput(properties: Record<string, unknown>): Record<string, unknown> {
  return map_0(properties);
}

/** UpdateDistribution (handlers) — input shape UpdateDistributionRequest */
export function buildUpdateInput(properties: Record<string, unknown>): Record<string, unknown> {
  return map_35(properties);
}

/** DeleteDistribution (handlers) — input shape DeleteDistributionRequest */
export function buildDeleteInput(properties: Record<string, unknown>): Record<string, unknown> {
  return map_36(properties);
}

