// Generated by scripts/poc-codegen for AWS::ECS::TaskDefinition — DO NOT EDIT

// Source models: CFn registry schema + ecs-2014-11-13.json

function toNum(v: unknown): number | undefined {
  if (v === undefined || v === null) return undefined;
  if (typeof v === 'number') return v;
  const n = Number(v);
  if (Number.isNaN(n)) throw new Error(`expected a number, got: ${JSON.stringify(v)}`);
  return n;
}
function toBool(v: unknown): boolean | undefined {
  if (v === undefined || v === null) return undefined;
  if (typeof v === 'boolean') return v;
  if (v === 'true' || v === 'True') return true;
  if (v === 'false' || v === 'False') return false;
  throw new Error(`expected a boolean, got: ${JSON.stringify(v)}`);
}
function toDateV(v: unknown): Date | undefined {
  if (v === undefined || v === null) return undefined;
  if (v instanceof Date) return v;
  const d = typeof v === 'string' || typeof v === 'number' ? new Date(v) : new Date(NaN);
  if (Number.isNaN(d.getTime())) throw new Error(`unparsable time value: ${JSON.stringify(v)}`);
  return d;
}
function toJsonString(v: unknown): string | undefined {
  if (v === undefined || v === null) return undefined;
  return typeof v === 'string' ? v : JSON.stringify(v);
}

// ContainerDependency -> ContainerDependency
function map_9(input: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  {
    const v = input['Condition'];
    if (v !== undefined) out['condition'] = v;
  }
  {
    const v = input['ContainerName'];
    if (v !== undefined) out['containerName'] = v;
  }
  return out;
}

// KeyValuePair -> KeyValuePair
function map_10(input: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  {
    const v = input['Name'];
    if (v !== undefined) out['name'] = v;
  }
  {
    const v = input['Value'];
    if (v !== undefined) out['value'] = v;
  }
  return out;
}

// EnvironmentFile -> EnvironmentFile
function map_11(input: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  {
    const v = input['Type'];
    if (v !== undefined) out['type'] = v;
  }
  {
    const v = input['Value'];
    if (v !== undefined) out['value'] = v;
  }
  return out;
}

// HostEntry -> HostEntry
function map_12(input: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  {
    const v = input['Hostname'];
    if (v !== undefined) out['hostname'] = v;
  }
  {
    const v = input['IpAddress'];
    if (v !== undefined) out['ipAddress'] = v;
  }
  return out;
}

// FirelensConfiguration -> FirelensConfiguration
function map_13(input: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  {
    const v = input['Options'];
    if (v !== undefined) out['options'] = v;
  }
  {
    const v = input['Type'];
    if (v !== undefined) out['type'] = v;
  }
  return out;
}

// HealthCheck -> HealthCheck
function map_14(input: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  {
    const v = input['Command'];
    if (v !== undefined) out['command'] = v;
  }
  {
    const v = input['Interval'];
    if (v !== undefined) out['interval'] = v;
  }
  {
    const v = input['Retries'];
    if (v !== undefined) out['retries'] = v;
  }
  {
    const v = input['StartPeriod'];
    if (v !== undefined) out['startPeriod'] = v;
  }
  {
    const v = input['Timeout'];
    if (v !== undefined) out['timeout'] = v;
  }
  return out;
}

// KernelCapabilities -> KernelCapabilities
function map_26(input: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  {
    const v = input['Add'];
    if (v !== undefined) out['add'] = v;
  }
  {
    const v = input['Drop'];
    if (v !== undefined) out['drop'] = v;
  }
  return out;
}

// Device -> Device
function map_27(input: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  {
    const v = input['ContainerPath'];
    if (v !== undefined) out['containerPath'] = v;
  }
  {
    const v = input['HostPath'];
    if (v !== undefined) out['hostPath'] = v;
  }
  {
    const v = input['Permissions'];
    if (v !== undefined) out['permissions'] = v;
  }
  return out;
}

// Tmpfs -> Tmpfs
function map_28(input: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  {
    const v = input['ContainerPath'];
    if (v !== undefined) out['containerPath'] = v;
  }
  {
    const v = input['MountOptions'];
    if (v !== undefined) out['mountOptions'] = v;
  }
  {
    const v = input['Size'];
    if (v !== undefined) out['size'] = v;
  }
  return out;
}

// LinuxParameters -> LinuxParameters
function map_15(input: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  {
    const v = input['Capabilities'];
    if (v !== undefined) out['capabilities'] = map_26(v as Record<string, unknown>);
  }
  {
    const v = input['Devices'];
    if (v !== undefined) out['devices'] = (v as unknown[]).map((e) => map_27(e as Record<string, unknown>));
  }
  {
    const v = input['InitProcessEnabled'];
    if (v !== undefined) out['initProcessEnabled'] = v;
  }
  {
    const v = input['MaxSwap'];
    if (v !== undefined) out['maxSwap'] = v;
  }
  {
    const v = input['SharedMemorySize'];
    if (v !== undefined) out['sharedMemorySize'] = v;
  }
  {
    const v = input['Swappiness'];
    if (v !== undefined) out['swappiness'] = v;
  }
  {
    const v = input['Tmpfs'];
    if (v !== undefined) out['tmpfs'] = (v as unknown[]).map((e) => map_28(e as Record<string, unknown>));
  }
  return out;
}

// Secret -> Secret
function map_22(input: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  {
    const v = input['Name'];
    if (v !== undefined) out['name'] = v;
  }
  {
    const v = input['ValueFrom'];
    if (v !== undefined) out['valueFrom'] = v;
  }
  return out;
}

// LogConfiguration -> LogConfiguration
function map_16(input: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  {
    const v = input['LogDriver'];
    if (v !== undefined) out['logDriver'] = v;
  }
  {
    const v = input['Options'];
    if (v !== undefined) out['options'] = v;
  }
  {
    const v = input['SecretOptions'];
    if (v !== undefined) out['secretOptions'] = (v as unknown[]).map((e) => map_22(e as Record<string, unknown>));
  }
  return out;
}

// MountPoint -> MountPoint
function map_17(input: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  {
    const v = input['ContainerPath'];
    if (v !== undefined) out['containerPath'] = v;
  }
  {
    const v = input['ReadOnly'];
    if (v !== undefined) out['readOnly'] = v;
  }
  {
    const v = input['SourceVolume'];
    if (v !== undefined) out['sourceVolume'] = v;
  }
  return out;
}

// PortMapping -> PortMapping
function map_18(input: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  {
    const v = input['AppProtocol'];
    if (v !== undefined) out['appProtocol'] = v;
  }
  {
    const v = input['ContainerPort'];
    if (v !== undefined) out['containerPort'] = v;
  }
  {
    const v = input['ContainerPortRange'];
    if (v !== undefined) out['containerPortRange'] = v;
  }
  {
    const v = input['HostPort'];
    if (v !== undefined) out['hostPort'] = v;
  }
  {
    const v = input['Name'];
    if (v !== undefined) out['name'] = v;
  }
  {
    const v = input['Protocol'];
    if (v !== undefined) out['protocol'] = v;
  }
  return out;
}

// RepositoryCredentials -> RepositoryCredentials
function map_19(input: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  {
    const v = input['CredentialsParameter'];
    if (v !== undefined) out['credentialsParameter'] = v;
  }
  return out;
}

// ResourceRequirement -> ResourceRequirement
function map_20(input: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  {
    const v = input['Type'];
    if (v !== undefined) out['type'] = v;
  }
  {
    const v = input['Value'];
    if (v !== undefined) out['value'] = v;
  }
  return out;
}

// RestartPolicy -> ContainerRestartPolicy
function map_21(input: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  {
    const v = input['Enabled'];
    if (v !== undefined) out['enabled'] = v;
  }
  {
    const v = input['IgnoredExitCodes'];
    if (v !== undefined) out['ignoredExitCodes'] = v;
  }
  {
    const v = input['RestartAttemptPeriod'];
    if (v !== undefined) out['restartAttemptPeriod'] = v;
  }
  return out;
}

// SystemControl -> SystemControl
function map_23(input: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  {
    const v = input['Namespace'];
    if (v !== undefined) out['namespace'] = v;
  }
  {
    const v = input['Value'];
    if (v !== undefined) out['value'] = v;
  }
  return out;
}

// Ulimit -> Ulimit
function map_24(input: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  {
    const v = input['HardLimit'];
    if (v !== undefined) out['hardLimit'] = v;
  }
  {
    const v = input['Name'];
    if (v !== undefined) out['name'] = v;
  }
  {
    const v = input['SoftLimit'];
    if (v !== undefined) out['softLimit'] = v;
  }
  return out;
}

// VolumeFrom -> VolumeFrom
function map_25(input: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  {
    const v = input['ReadOnly'];
    if (v !== undefined) out['readOnly'] = v;
  }
  {
    const v = input['SourceContainer'];
    if (v !== undefined) out['sourceContainer'] = v;
  }
  return out;
}

// ContainerDefinition -> ContainerDefinition
function map_1(input: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  {
    const v = input['Command'];
    if (v !== undefined) out['command'] = v;
  }
  {
    const v = input['Cpu'];
    if (v !== undefined) out['cpu'] = v;
  }
  {
    const v = input['CredentialSpecs'];
    if (v !== undefined) out['credentialSpecs'] = v;
  }
  {
    const v = input['DependsOn'];
    if (v !== undefined) out['dependsOn'] = (v as unknown[]).map((e) => map_9(e as Record<string, unknown>));
  }
  {
    const v = input['DisableNetworking'];
    if (v !== undefined) out['disableNetworking'] = v;
  }
  {
    const v = input['DnsSearchDomains'];
    if (v !== undefined) out['dnsSearchDomains'] = v;
  }
  {
    const v = input['DnsServers'];
    if (v !== undefined) out['dnsServers'] = v;
  }
  {
    const v = input['DockerLabels'];
    if (v !== undefined) out['dockerLabels'] = v;
  }
  {
    const v = input['DockerSecurityOptions'];
    if (v !== undefined) out['dockerSecurityOptions'] = v;
  }
  {
    const v = input['EntryPoint'];
    if (v !== undefined) out['entryPoint'] = v;
  }
  {
    const v = input['Environment'];
    if (v !== undefined) out['environment'] = (v as unknown[]).map((e) => map_10(e as Record<string, unknown>));
  }
  {
    const v = input['EnvironmentFiles'];
    if (v !== undefined) out['environmentFiles'] = (v as unknown[]).map((e) => map_11(e as Record<string, unknown>));
  }
  {
    const v = input['Essential'];
    if (v !== undefined) out['essential'] = v;
  }
  {
    const v = input['ExtraHosts'];
    if (v !== undefined) out['extraHosts'] = (v as unknown[]).map((e) => map_12(e as Record<string, unknown>));
  }
  {
    const v = input['FirelensConfiguration'];
    if (v !== undefined) out['firelensConfiguration'] = map_13(v as Record<string, unknown>);
  }
  {
    const v = input['HealthCheck'];
    if (v !== undefined) out['healthCheck'] = map_14(v as Record<string, unknown>);
  }
  {
    const v = input['Hostname'];
    if (v !== undefined) out['hostname'] = v;
  }
  {
    const v = input['Image'];
    if (v !== undefined) out['image'] = v;
  }
  {
    const v = input['Interactive'];
    if (v !== undefined) out['interactive'] = v;
  }
  {
    const v = input['Links'];
    if (v !== undefined) out['links'] = v;
  }
  {
    const v = input['LinuxParameters'];
    if (v !== undefined) out['linuxParameters'] = map_15(v as Record<string, unknown>);
  }
  {
    const v = input['LogConfiguration'];
    if (v !== undefined) out['logConfiguration'] = map_16(v as Record<string, unknown>);
  }
  {
    const v = input['Memory'];
    if (v !== undefined) out['memory'] = v;
  }
  {
    const v = input['MemoryReservation'];
    if (v !== undefined) out['memoryReservation'] = v;
  }
  {
    const v = input['MountPoints'];
    if (v !== undefined) out['mountPoints'] = (v as unknown[]).map((e) => map_17(e as Record<string, unknown>));
  }
  {
    const v = input['Name'];
    if (v !== undefined) out['name'] = v;
  }
  {
    const v = input['PortMappings'];
    if (v !== undefined) out['portMappings'] = (v as unknown[]).map((e) => map_18(e as Record<string, unknown>));
  }
  {
    const v = input['Privileged'];
    if (v !== undefined) out['privileged'] = v;
  }
  {
    const v = input['PseudoTerminal'];
    if (v !== undefined) out['pseudoTerminal'] = v;
  }
  {
    const v = input['ReadonlyRootFilesystem'];
    if (v !== undefined) out['readonlyRootFilesystem'] = v;
  }
  {
    const v = input['RepositoryCredentials'];
    if (v !== undefined) out['repositoryCredentials'] = map_19(v as Record<string, unknown>);
  }
  {
    const v = input['ResourceRequirements'];
    if (v !== undefined) out['resourceRequirements'] = (v as unknown[]).map((e) => map_20(e as Record<string, unknown>));
  }
  {
    const v = input['RestartPolicy'];
    if (v !== undefined) out['restartPolicy'] = map_21(v as Record<string, unknown>);
  }
  {
    const v = input['Secrets'];
    if (v !== undefined) out['secrets'] = (v as unknown[]).map((e) => map_22(e as Record<string, unknown>));
  }
  {
    const v = input['StartTimeout'];
    if (v !== undefined) out['startTimeout'] = v;
  }
  {
    const v = input['StopTimeout'];
    if (v !== undefined) out['stopTimeout'] = v;
  }
  {
    const v = input['SystemControls'];
    if (v !== undefined) out['systemControls'] = (v as unknown[]).map((e) => map_23(e as Record<string, unknown>));
  }
  {
    const v = input['Ulimits'];
    if (v !== undefined) out['ulimits'] = (v as unknown[]).map((e) => map_24(e as Record<string, unknown>));
  }
  {
    const v = input['User'];
    if (v !== undefined) out['user'] = v;
  }
  {
    const v = input['VersionConsistency'];
    if (v !== undefined) out['versionConsistency'] = v;
  }
  {
    const v = input['VolumesFrom'];
    if (v !== undefined) out['volumesFrom'] = (v as unknown[]).map((e) => map_25(e as Record<string, unknown>));
  }
  {
    const v = input['WorkingDirectory'];
    if (v !== undefined) out['workingDirectory'] = v;
  }
  return out;
}

// EphemeralStorage -> EphemeralStorage
function map_2(input: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  {
    const v = input['SizeInGiB'];
    if (v !== undefined) out['sizeInGiB'] = v;
  }
  return out;
}

// InferenceAccelerator -> InferenceAccelerator
function map_3(input: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  {
    const v = input['DeviceName'];
    if (v !== undefined) out['deviceName'] = v;
  }
  {
    const v = input['DeviceType'];
    if (v !== undefined) out['deviceType'] = v;
  }
  return out;
}

// TaskDefinitionPlacementConstraint -> TaskDefinitionPlacementConstraint
function map_4(input: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  {
    const v = input['Expression'];
    if (v !== undefined) out['expression'] = v;
  }
  {
    const v = input['Type'];
    if (v !== undefined) out['type'] = v;
  }
  return out;
}

// ProxyConfiguration -> ProxyConfiguration
function map_5(input: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  {
    const v = input['ContainerName'];
    if (v !== undefined) out['containerName'] = v;
  }
  // RENAME-CANDIDATE (NOT emitted; confirm via override table): 'ProxyConfigurationProperties' -> 'properties' (fuzzy-matched to "properties" (overlap 0.36))
  {
    const v = input['Type'];
    if (v !== undefined) out['type'] = v;
  }
  return out;
}

// RuntimePlatform -> RuntimePlatform
function map_6(input: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  {
    const v = input['CpuArchitecture'];
    if (v !== undefined) out['cpuArchitecture'] = v;
  }
  {
    const v = input['OperatingSystemFamily'];
    if (v !== undefined) out['operatingSystemFamily'] = v;
  }
  return out;
}

// Tag -> Tag
function map_7(input: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  {
    const v = input['Key'];
    if (v !== undefined) out['key'] = v;
  }
  {
    const v = input['Value'];
    if (v !== undefined) out['value'] = v;
  }
  return out;
}

// DockerVolumeConfiguration -> DockerVolumeConfiguration
function map_29(input: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  {
    const v = input['Autoprovision'];
    if (v !== undefined) out['autoprovision'] = v;
  }
  {
    const v = input['Driver'];
    if (v !== undefined) out['driver'] = v;
  }
  {
    const v = input['DriverOpts'];
    if (v !== undefined) out['driverOpts'] = v;
  }
  {
    const v = input['Labels'];
    if (v !== undefined) out['labels'] = v;
  }
  {
    const v = input['Scope'];
    if (v !== undefined) out['scope'] = v;
  }
  return out;
}

// AuthorizationConfig -> EFSAuthorizationConfig
function map_34(input: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  {
    const v = input['AccessPointId'];
    if (v !== undefined) out['accessPointId'] = v;
  }
  // case-divergence: 'IAM' -> 'iam'
  {
    const v = input['IAM'];
    if (v !== undefined) out['iam'] = v;
  }
  return out;
}

// EFSVolumeConfiguration -> EFSVolumeConfiguration
function map_30(input: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  {
    const v = input['AuthorizationConfig'];
    if (v !== undefined) out['authorizationConfig'] = map_34(v as Record<string, unknown>);
  }
  // case-divergence: 'FilesystemId' -> 'fileSystemId'
  {
    const v = input['FilesystemId'];
    if (v !== undefined) out['fileSystemId'] = v;
  }
  {
    const v = input['RootDirectory'];
    if (v !== undefined) out['rootDirectory'] = v;
  }
  {
    const v = input['TransitEncryption'];
    if (v !== undefined) out['transitEncryption'] = v;
  }
  {
    const v = input['TransitEncryptionPort'];
    if (v !== undefined) out['transitEncryptionPort'] = v;
  }
  return out;
}

// FSxAuthorizationConfig -> FSxWindowsFileServerAuthorizationConfig
function map_35(input: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  {
    const v = input['CredentialsParameter'];
    if (v !== undefined) out['credentialsParameter'] = v;
  }
  {
    const v = input['Domain'];
    if (v !== undefined) out['domain'] = v;
  }
  return out;
}

// FSxWindowsFileServerVolumeConfiguration -> FSxWindowsFileServerVolumeConfiguration
function map_31(input: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  {
    const v = input['AuthorizationConfig'];
    if (v !== undefined) out['authorizationConfig'] = map_35(v as Record<string, unknown>);
  }
  {
    const v = input['FileSystemId'];
    if (v !== undefined) out['fileSystemId'] = v;
  }
  {
    const v = input['RootDirectory'];
    if (v !== undefined) out['rootDirectory'] = v;
  }
  return out;
}

// HostVolumeProperties -> HostVolumeProperties
function map_32(input: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  {
    const v = input['SourcePath'];
    if (v !== undefined) out['sourcePath'] = v;
  }
  return out;
}

// S3FilesVolumeConfiguration -> S3FilesVolumeConfiguration
function map_33(input: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  {
    const v = input['AccessPointArn'];
    if (v !== undefined) out['accessPointArn'] = v;
  }
  {
    const v = input['FileSystemArn'];
    if (v !== undefined) out['fileSystemArn'] = v;
  }
  {
    const v = input['RootDirectory'];
    if (v !== undefined) out['rootDirectory'] = v;
  }
  {
    const v = input['TransitEncryptionPort'];
    if (v !== undefined) out['transitEncryptionPort'] = v;
  }
  return out;
}

// Volume -> Volume
function map_8(input: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  {
    const v = input['ConfiguredAtLaunch'];
    if (v !== undefined) out['configuredAtLaunch'] = v;
  }
  {
    const v = input['DockerVolumeConfiguration'];
    if (v !== undefined) out['dockerVolumeConfiguration'] = map_29(v as Record<string, unknown>);
  }
  // case-divergence: 'EFSVolumeConfiguration' -> 'efsVolumeConfiguration'
  {
    const v = input['EFSVolumeConfiguration'];
    if (v !== undefined) out['efsVolumeConfiguration'] = map_30(v as Record<string, unknown>);
  }
  // case-divergence: 'FSxWindowsFileServerVolumeConfiguration' -> 'fsxWindowsFileServerVolumeConfiguration'
  {
    const v = input['FSxWindowsFileServerVolumeConfiguration'];
    if (v !== undefined) out['fsxWindowsFileServerVolumeConfiguration'] = map_31(v as Record<string, unknown>);
  }
  {
    const v = input['Host'];
    if (v !== undefined) out['host'] = map_32(v as Record<string, unknown>);
  }
  {
    const v = input['Name'];
    if (v !== undefined) out['name'] = v;
  }
  // case-divergence: 'S3FilesVolumeConfiguration' -> 's3filesVolumeConfiguration'
  {
    const v = input['S3FilesVolumeConfiguration'];
    if (v !== undefined) out['s3filesVolumeConfiguration'] = map_33(v as Record<string, unknown>);
  }
  return out;
}

// #top(RegisterTaskDefinition) -> RegisterTaskDefinitionRequest
function map_0(input: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  {
    const v = input['ContainerDefinitions'];
    if (v !== undefined) out['containerDefinitions'] = (v as unknown[]).map((e) => map_1(e as Record<string, unknown>));
  }
  {
    const v = input['Cpu'];
    if (v !== undefined) out['cpu'] = v;
  }
  {
    const v = input['EnableFaultInjection'];
    if (v !== undefined) out['enableFaultInjection'] = v;
  }
  {
    const v = input['EphemeralStorage'];
    if (v !== undefined) out['ephemeralStorage'] = map_2(v as Record<string, unknown>);
  }
  {
    const v = input['ExecutionRoleArn'];
    if (v !== undefined) out['executionRoleArn'] = v;
  }
  {
    const v = input['Family'];
    if (v !== undefined) out['family'] = v;
  }
  {
    const v = input['InferenceAccelerators'];
    if (v !== undefined) out['inferenceAccelerators'] = (v as unknown[]).map((e) => map_3(e as Record<string, unknown>));
  }
  {
    const v = input['IpcMode'];
    if (v !== undefined) out['ipcMode'] = v;
  }
  {
    const v = input['Memory'];
    if (v !== undefined) out['memory'] = v;
  }
  {
    const v = input['NetworkMode'];
    if (v !== undefined) out['networkMode'] = v;
  }
  {
    const v = input['PidMode'];
    if (v !== undefined) out['pidMode'] = v;
  }
  {
    const v = input['PlacementConstraints'];
    if (v !== undefined) out['placementConstraints'] = (v as unknown[]).map((e) => map_4(e as Record<string, unknown>));
  }
  {
    const v = input['ProxyConfiguration'];
    if (v !== undefined) out['proxyConfiguration'] = map_5(v as Record<string, unknown>);
  }
  {
    const v = input['RequiresCompatibilities'];
    if (v !== undefined) out['requiresCompatibilities'] = v;
  }
  {
    const v = input['RuntimePlatform'];
    if (v !== undefined) out['runtimePlatform'] = map_6(v as Record<string, unknown>);
  }
  {
    const v = input['Tags'];
    if (v !== undefined) out['tags'] = (v as unknown[]).map((e) => map_7(e as Record<string, unknown>));
  }
  {
    const v = input['TaskRoleArn'];
    if (v !== undefined) out['taskRoleArn'] = v;
  }
  {
    const v = input['Volumes'];
    if (v !== undefined) out['volumes'] = (v as unknown[]).map((e) => map_8(e as Record<string, unknown>));
  }
  return out;
}

// #top(DeregisterTaskDefinition) -> DeregisterTaskDefinitionRequest
function map_36(input: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  // UNMATCHED: 'ContainerDefinitions' (list) — no SDK member; verify: CFn-only field or silent drop
  // UNMATCHED: 'Cpu' (string) — no SDK member; verify: CFn-only field or silent drop
  // UNMATCHED: 'EnableFaultInjection' (boolean) — no SDK member; verify: CFn-only field or silent drop
  // UNMATCHED: 'EphemeralStorage' (structure) — no SDK member; verify: CFn-only field or silent drop
  // UNMATCHED: 'ExecutionRoleArn' (string) — no SDK member; verify: CFn-only field or silent drop
  // UNMATCHED: 'Family' (string) — no SDK member; verify: CFn-only field or silent drop
  // UNMATCHED: 'InferenceAccelerators' (list) — no SDK member; verify: CFn-only field or silent drop
  // UNMATCHED: 'IpcMode' (string) — no SDK member; verify: CFn-only field or silent drop
  // UNMATCHED: 'Memory' (string) — no SDK member; verify: CFn-only field or silent drop
  // UNMATCHED: 'NetworkMode' (string) — no SDK member; verify: CFn-only field or silent drop
  // UNMATCHED: 'PidMode' (string) — no SDK member; verify: CFn-only field or silent drop
  // UNMATCHED: 'PlacementConstraints' (list) — no SDK member; verify: CFn-only field or silent drop
  // UNMATCHED: 'ProxyConfiguration' (structure) — no SDK member; verify: CFn-only field or silent drop
  // UNMATCHED: 'RequiresCompatibilities' (list) — no SDK member; verify: CFn-only field or silent drop
  // UNMATCHED: 'RuntimePlatform' (structure) — no SDK member; verify: CFn-only field or silent drop
  // UNMATCHED: 'Tags' (list) — no SDK member; verify: CFn-only field or silent drop
  // UNMATCHED: 'TaskRoleArn' (string) — no SDK member; verify: CFn-only field or silent drop
  // UNMATCHED: 'Volumes' (list) — no SDK member; verify: CFn-only field or silent drop
  // TODO(required): SDK member 'taskDefinition' has no CFn source — synthesize it
  return out;
}

/** RegisterTaskDefinition (handlers) — input shape RegisterTaskDefinitionRequest */
export function buildCreateInput(properties: Record<string, unknown>): Record<string, unknown> {
  return map_0(properties);
}

/** DeregisterTaskDefinition (handlers) — input shape DeregisterTaskDefinitionRequest */
export function buildDeleteInput(properties: Record<string, unknown>): Record<string, unknown> {
  return map_36(properties);
}

