/**
 * TypeScript mapper emitter: projects a ResourceMappingSpec into readable,
 * dependency-free mapper code — the shape a production generator would ship
 * (one `buildXxxInput(properties)` per operation, one `map_N` per
 * (CFn definition, SDK shape) pair).
 */
import type { MemberMapping, ResourceMappingSpec, StructMapping } from './types.ts';

const HELPERS = `
function toNum(v: unknown): number | undefined {
  if (v === undefined || v === null) return undefined;
  if (typeof v === 'number') return v;
  const n = Number(v);
  if (Number.isNaN(n)) throw new Error(\`expected a number, got: \${JSON.stringify(v)}\`);
  return n;
}
function toBool(v: unknown): boolean | undefined {
  if (v === undefined || v === null) return undefined;
  if (typeof v === 'boolean') return v;
  if (v === 'true') return true;
  if (v === 'false') return false;
  throw new Error(\`expected a boolean, got: \${JSON.stringify(v)}\`);
}
function toDateV(v: unknown): Date | undefined {
  if (v === undefined || v === null) return undefined;
  if (v instanceof Date) return v;
  const d = typeof v === 'string' || typeof v === 'number' ? new Date(v) : new Date(NaN);
  if (Number.isNaN(d.getTime())) throw new Error(\`unparsable time value: \${JSON.stringify(v)}\`);
  return d;
}
function toJsonString(v: unknown): string | undefined {
  if (v === undefined || v === null) return undefined;
  return typeof v === 'string' ? v : JSON.stringify(v);
}
`;

/** Case match that is JUST the leading-character style flip (Pascal->camel). */
function isStyleFlip(cfn: string, sdk: string): boolean {
  return cfn.length > 0 && cfn.charAt(0).toLowerCase() + cfn.slice(1) === sdk;
}

export function emitMapper(
  spec: ResourceMappingSpec,
  entryNames: Partial<Record<'create' | 'update' | 'delete', string>>
): string {
  const fnName = new Map<string, string>();
  let counter = 0;
  const nameFor = (id: string): string => {
    let name = fnName.get(id);
    if (name === undefined) {
      name = `map_${counter++}`;
      fnName.set(id, name);
    }
    return name;
  };

  const emitted = new Set<string>();
  const lines: string[] = [];

  const emitStruct = (id: string): void => {
    if (emitted.has(id)) return;
    emitted.add(id);
    const struct = spec.structs[id] as StructMapping;
    const children: string[] = [];
    const body: string[] = [];
    body.push(`// ${struct.cfnDef} -> ${struct.sdkShape}`);
    body.push(
      `function ${nameFor(id)}(input: Record<string, unknown>): Record<string, unknown> {`
    );
    body.push(`  const out: Record<string, unknown> = {};`);
    for (const m of struct.members) {
      emitMember(m, body, children, nameFor);
    }
    for (const req of struct.sdkRequiredUnfed) {
      body.push(`  // TODO(required): SDK member '${req}' has no CFn source — synthesize it`);
    }
    body.push(`  return out;`);
    body.push(`}`);
    // Depth-first: children first so the file reads bottom-up like the
    // hand-written providers do.
    for (const child of children) emitStruct(child);
    lines.push(body.join('\n'));
  };

  const entries: string[] = [];
  for (const kind of ['create', 'update', 'delete'] as const) {
    const op = spec.operations[kind];
    const entry = entryNames[kind];
    if (op === undefined || entry === undefined) continue;
    emitStruct(op.rootId);
    entries.push(
      `/** ${op.operationName} (${op.source}) — input shape ${op.inputShape.split('#')[1]} */\n` +
        `export function ${entry}(properties: Record<string, unknown>): Record<string, unknown> {\n` +
        `  return ${nameFor(op.rootId)}(properties);\n}`
    );
  }

  return [
    `// Generated by scripts/poc-codegen for ${spec.resourceType} — DO NOT EDIT`,
    `// Source models: CFn registry schema + ${spec.service.modelPath.split('/').slice(-1)[0]}`,
    HELPERS.trim(),
    ...lines,
    ...entries,
    '',
  ].join('\n\n');
}

function emitMember(
  m: MemberMapping,
  body: string[],
  children: string[],
  nameFor: (id: string) => string
): void {
  if (m.sdk === null) {
    body.push(
      `  // UNMATCHED: '${m.cfn}' (${m.cfnKind}) — no SDK member; ` +
        `verify: CFn-only field or silent drop`
    );
    return;
  }
  if (m.transform === 'unsupported') {
    body.push(
      `  // UNSUPPORTED: '${m.cfn}' -> '${m.sdk}' (${m.notes.join('; ') || 'manual mapping needed'})`
    );
    return;
  }
  const comments: string[] = [];
  if (m.match === 'case' && !isStyleFlip(m.cfn, m.sdk)) {
    comments.push(`case-divergence: '${m.cfn}' -> '${m.sdk}'`);
  }
  if (m.match === 'rename-candidate') {
    comments.push(`RENAME-CANDIDATE (confirm): '${m.cfn}' -> '${m.sdk}'`);
  }
  for (const note of m.notes) comments.push(note);

  const v = `input['${m.cfn}']`;
  let expr: string;
  switch (m.transform) {
    case 'direct':
    case 'document':
    case 'map':
      expr = 'v';
      break;
    case 'structure':
      expr =
        m.childId !== undefined
          ? (children.push(m.childId), `${nameFor(m.childId)}(v as Record<string, unknown>)`)
          : 'v';
      break;
    case 'list':
      expr =
        m.childId !== undefined
          ? (children.push(m.childId),
            `(v as unknown[]).map((e) => ${nameFor(m.childId)}(e as Record<string, unknown>))`)
          : 'v';
      break;
    case 'wrap-quantity-items':
    case 'wrap-single-list-member': {
      const w = m.wrapper as NonNullable<MemberMapping['wrapper']>;
      const items =
        m.childId !== undefined
          ? (children.push(m.childId),
            `(v as unknown[]).map((e) => ${nameFor(m.childId)}(e as Record<string, unknown>))`)
          : `v`;
      expr =
        w.quantityMember !== null
          ? `{ ${w.quantityMember}: (v as unknown[]).length, ${w.itemsMember}: ${items} }`
          : `{ ${w.itemsMember}: ${items} }`;
      break;
    }
    case 'to-date':
      expr = 'toDateV(v)';
      break;
    case 'coerce-number':
      expr = 'toNum(v)';
      break;
    case 'coerce-boolean':
      expr = 'toBool(v)';
      break;
    case 'to-string':
      expr = 'String(v)';
      break;
    case 'json-string':
      expr = 'toJsonString(v)';
      break;
    default:
      expr = 'v';
  }

  for (const c of comments) body.push(`  // ${c}`);
  body.push(`  {`);
  body.push(`    const v = ${v};`);
  if (
    (m.transform === 'wrap-quantity-items' || m.transform === 'wrap-single-list-member') &&
    m.sdkRequired
  ) {
    const w = m.wrapper as NonNullable<MemberMapping['wrapper']>;
    const empty =
      w.quantityMember !== null
        ? `{ ${w.quantityMember}: 0, ${w.itemsMember}: [] }`
        : `{ ${w.itemsMember}: [] }`;
    body.push(`    if (v !== undefined) out['${m.sdk}'] = ${expr};`);
    body.push(`    else out['${m.sdk}'] = ${empty}; // required wrapper: empty default`);
  } else {
    body.push(`    if (v !== undefined) out['${m.sdk}'] = ${expr};`);
  }
  body.push(`  }`);
}
